"""Initial migration - Create all database tables

Revision ID: 37d437544626
Revises: 
Create Date: 2026-01-30 20:59:03.041899

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '37d437544626'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('api_scopes',
    sa.Column('id', sa.UUID(), nullable=False, comment='Global unique UUID for API scope'),
    sa.Column('scope', sa.String(length=100), nullable=False, comment="Scope identifier (e.g., 'tasks:read', 'tasks:write', 'projects:read')"),
    sa.Column('description', sa.Text(), nullable=True, comment='Scope description'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Timestamp when the record was created'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Timestamp when the record was last updated'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_api_scopes'))
    )
    op.create_index(op.f('ix_api_scopes_scope'), 'api_scopes', ['scope'], unique=True)
    op.create_table('auth_providers',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Timestamp when the record was created'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Timestamp when the record was last updated'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_auth_providers')),
    sa.UniqueConstraint('name', name=op.f('uq_auth_providers_name'))
    )
    op.create_table('domain_events',
    sa.Column('id', sa.UUID(), nullable=False, comment='Global unique UUID for domain event'),
    sa.Column('event_type', sa.String(length=100), nullable=False, comment="Type of event (e.g., 'task.created', 'user.invited')"),
    sa.Column('aggregate_id', sa.UUID(), nullable=False, comment='ID of the aggregate root that triggered the event'),
    sa.Column('aggregate_type', sa.String(length=100), nullable=False, comment="Type of aggregate (e.g., 'Task', 'User')"),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False, comment='Event data payload'),
    sa.Column('meta', postgresql.JSONB(astext_type=sa.Text()), nullable=False, comment='Additional metadata (user_id, ip_address, etc.)'),
    sa.Column('is_published', sa.Boolean(), nullable=False, comment='Whether event has been published to consumers'),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True, comment='Timestamp when event was published'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Timestamp when the record was created'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Timestamp when the record was last updated'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_domain_events'))
    )
    op.create_index('ix_domain_events_aggregate_id', 'domain_events', ['aggregate_id'], unique=False)
    op.create_index('ix_domain_events_event_type', 'domain_events', ['event_type'], unique=False)
    op.create_index('ix_domain_events_is_published', 'domain_events', ['is_published'], unique=False)
    op.create_table('notification_templates',
    sa.Column('id', sa.UUID(), nullable=False, comment='Global unique UUID for notification template'),
    sa.Column('name', sa.String(length=100), nullable=False, comment="Template name (e.g., 'task_assigned', 'comment_added')"),
    sa.Column('description', sa.Text(), nullable=True, comment='Template description'),
    sa.Column('title_template', sa.Text(), nullable=False, comment="Title template with placeholders (e.g., 'Task {task_title} assigned to you')"),
    sa.Column('content_template', sa.Text(), nullable=False, comment='Content template with placeholders (rich-text HTML/JSON)'),
    sa.Column('variables', postgresql.JSONB(astext_type=sa.Text()), nullable=False, comment='Available variables for substitution'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Timestamp when the record was created'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Timestamp when the record was last updated'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_notification_templates')),
    sa.UniqueConstraint('name', name=op.f('uq_notification_templates_name'))
    )
    op.create_table('permissions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('code', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_permissions'))
    )
    op.create_index(op.f('ix_permissions_code'), 'permissions', ['code'], unique=True)
    op.create_table('roles',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('role_name', sa.String(length=50), nullable=False),
    sa.Column('hierarchy_level', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_roles')),
    sa.UniqueConstraint('role_name', name=op.f('uq_roles_role_name'))
    )
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False, comment='Primary key UUID for the user.'),
    sa.Column('email', sa.String(length=255), nullable=False, comment="User's email address."),
    sa.Column('username', sa.String(length=255), nullable=False, comment="User's username."),
    sa.Column('password_hash', sa.String(length=255), nullable=True, comment='Hashed password for local authentication.'),
    sa.Column('status', sa.Enum('PENDING', 'ACTIVE', 'INACTIVE', 'SUSPENDED', 'DELETED', name='userstatus'), nullable=False),
    sa.Column('email_verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Timestamp when the record was created'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Timestamp when the record was last updated'),
    sa.Column('is_deleted', sa.Boolean(), nullable=False, comment='Flag indicating soft deletion status'),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True, comment='Timestamp when the record was soft deleted'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users'))
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_is_deleted'), 'users', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('webhook_events',
    sa.Column('id', sa.UUID(), nullable=False, comment='Global unique UUID for webhook event'),
    sa.Column('event_type', sa.String(length=100), nullable=False, comment="Event type (e.g., 'task.created', 'project.updated')"),
    sa.Column('description', sa.Text(), nullable=True, comment='Event description'),
    sa.Column('payload_schema', postgresql.JSONB(astext_type=sa.Text()), nullable=False, comment='JSON Schema for event payload'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Timestamp when the record was created'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Timestamp when the record was last updated'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_webhook_events'))
    )
    op.create_index(op.f('ix_webhook_events_event_type'), 'webhook_events', ['event_type'], unique=True)
    op.create_table('api_tokens',
    sa.Column('id', sa.UUID(), nullable=False, comment='Global unique UUID for API token'),
    sa.Column('user_id', sa.UUID(), nullable=False, comment='Token owner'),
    sa.Column('name', sa.String(length=100), nullable=False, comment="Token name (e.g., 'CI Bot', 'Mobile App')"),
    sa.Column('token_hash', sa.String(length=255), nullable=False, comment='Hashed token (never store plaintext)'),
    sa.Column('last_used_at', sa.DateTime(timezone=True), nullable=True, comment='Timestamp of last use'),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True, comment='Token expiration date (nullable = no expiration)'),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True, comment='Timestamp when token was revoked'),
    sa.Column('is_revoked', sa.Boolean(), nullable=False, comment='Whether token is revoked'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Timestamp when the record was created'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Timestamp when the record was last updated'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_api_tokens_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_api_tokens')),
    sa.UniqueConstraint('token_hash', name=op.f('uq_api_tokens_token_hash'))
    )
    op.create_index(op.f('ix_api_tokens_is_revoked'), 'api_tokens', ['is_revoked'], unique=False)
    op.create_index(op.f('ix_api_tokens_user_id'), 'api_tokens', ['user_id'], unique=False)
    op.create_table('audit_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('entity_type', sa.String(length=100), nullable=False),
    sa.Column('entity_id', sa.UUID(), nullable=False),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Timestamp when the record was created'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Timestamp when the record was last updated'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_audit_logs_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_audit_logs'))
    )
    op.create_table('event_consumers',
    sa.Column('id', sa.UUID(), nullable=False, comment='Global unique UUID for event consumer'),
    sa.Column('event_id', sa.UUID(), nullable=False, comment='Reference to domain event'),
    sa.Column('consumer_name', sa.String(length=100), nullable=False, comment='Name of the consumer service/handler'),
    sa.Column('status', sa.Enum('PENDING', 'PROCESSING', 'SUCCEEDED', 'FAILED', name='event_consumer_status'), nullable=False, comment='Processing status'),
    sa.Column('retry_count', sa.Integer(), nullable=False, comment='Number of retry attempts'),
    sa.Column('error_message', sa.Text(), nullable=True, comment='Error message if processing failed'),
    sa.Column('processed_at', sa.DateTime(timezone=True), nullable=True, comment='Timestamp when event was processed'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Timestamp when the record was created'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Timestamp when the record was last updated'),
    sa.ForeignKeyConstraint(['event_id'], ['domain_events.id'], name=op.f('fk_event_consumers_event_id_domain_events'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_event_consumers'))
    )
    op.create_index('ix_event_consumers_consumer_name', 'event_consumers', ['consumer_name'], unique=False)
    op.create_index('ix_event_consumers_event_id', 'event_consumers', ['event_id'], unique=False)
    op.create_index(op.f('ix_event_consumers_status'), 'event_consumers', ['status'], unique=False)
    op.create_table('mfa_configs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('secret_key', sa.String(length=255), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_mfa_configs_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_mfa_configs'))
    )
    op.create_table('notification_preferences',
    sa.Column('id', sa.UUID(), nullable=False, comment='Global unique UUID for notification preference'),
    sa.Column('user_id', sa.UUID(), nullable=False, comment='Reference to user'),
    sa.Column('notify_task_assigned', sa.Boolean(), nullable=False, comment='Notify when task is assigned'),
    sa.Column('notify_task_completed', sa.Boolean(), nullable=False, comment='Notify when task is completed'),
    sa.Column('notify_comment_reply', sa.Boolean(), nullable=False, comment='Notify on comment replies'),
    sa.Column('notify_mention', sa.Boolean(), nullable=False, comment='Notify when mentioned'),
    sa.Column('notify_workspace_update', sa.Boolean(), nullable=False, comment='Notify on workspace updates'),
    sa.Column('email_notifications', sa.Boolean(), nullable=False, comment='Enable email notifications'),
    sa.Column('in_app_notifications', sa.Boolean(), nullable=False, comment='Enable in-app notifications'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Timestamp when the record was created'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Timestamp when the record was last updated'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_notification_preferences_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_notification_preferences')),
    sa.UniqueConstraint('user_id', name=op.f('uq_notification_preferences_user_id'))
    )
    op.create_table('notifications',
    sa.Column('id', sa.UUID(), nullable=False, comment='Global unique UUID for notification'),
    sa.Column('user_id', sa.UUID(), nullable=False, comment='Notification receiver'),
    sa.Column('event_id', sa.UUID(), nullable=True, comment='Reference to domain event'),
    sa.Column('title', sa.String(length=255), nullable=False, comment='Notification title (rendered)'),
    sa.Column('content', sa.Text(), nullable=False, comment='Notification content (rendered HTML/JSON)'),
    sa.Column('priority', sa.Enum('LOW', 'MEDIUM', 'HIGH', 'URGENT', name='notification_priority'), nullable=False, comment='Notification priority level'),
    sa.Column('is_read', sa.Boolean(), nullable=False, comment='Whether notification has been read'),
    sa.Column('read_at', sa.DateTime(timezone=True), nullable=True, comment='Timestamp when notification was read'),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True, comment='TTL - when notification expires and can be deleted'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Timestamp when the record was created'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Timestamp when the record was last updated'),
    sa.ForeignKeyConstraint(['event_id'], ['domain_events.id'], name=op.f('fk_notifications_event_id_domain_events'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_notifications_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_notifications'))
    )
    op.create_index('ix_notifications_created_at', 'notifications', ['created_at'], unique=False)
    op.create_index('ix_notifications_is_read', 'notifications', ['is_read'], unique=False)
    op.create_index(op.f('ix_notifications_user_id'), 'notifications', ['user_id'], unique=False)
    op.create_table('role_permissions',
    sa.Column('role_id', sa.UUID(), nullable=False),
    sa.Column('permission_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['permission_id'], ['permissions.id'], name=op.f('fk_role_permissions_permission_id_permissions')),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], name=op.f('fk_role_permissions_role_id_roles')),
    sa.PrimaryKeyConstraint('role_id', 'permission_id', name=op.f('pk_role_permissions'))
    )
    op.create_table('sessions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('device_info', sa.String(length=255), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('geo_location', sa.String(length=100), nullable=True),
    sa.Column('last_active_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_current', sa.Boolean(), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Timestamp when the record was created'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Timestamp when the record was last updated'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_sessions_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_sessions'))
    )
    op.create_table('timesheets',
    sa.Column('id', sa.UUID(), nullable=False, comment='Global unique UUID for timesheet'),
    sa.Column('user_id', sa.UUID(), nullable=False, comment='Reference to user'),
    sa.Column('period_start', sa.Date(), nullable=False, comment='Start date of timesheet period'),
    sa.Column('period_end', sa.Date(), nullable=False, comment='End date of timesheet period'),
    sa.Column('total_hours', sa.Float(), nullable=False, comment='Total hours logged in this period'),
    sa.Column('status', sa.Enum('DRAFT', 'SUBMITTED', 'APPROVED', 'REJECTED', name='timesheet_status'), nullable=False, comment='Timesheet status (DRAFT / SUBMITTED / APPROVED / REJECTED)'),
    sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=True, comment='When timesheet was submitted'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Timestamp when the record was created'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Timestamp when the record was last updated'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_timesheets_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_timesheets'))
    )
    op.create_index('ix_timesheets_period_end', 'timesheets', ['period_end'], unique=False)
    op.create_index('ix_timesheets_period_start', 'timesheets', ['period_start'], unique=False)
    op.create_index('ix_timesheets_status', 'timesheets', ['status'], unique=False)
    op.create_index(op.f('ix_timesheets_user_id'), 'timesheets', ['user_id'], unique=False)
    op.create_table('user_roles',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('role_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], name=op.f('fk_user_roles_role_id_roles')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_user_roles_user_id_users')),
    sa.PrimaryKeyConstraint('user_id', 'role_id', name=op.f('pk_user_roles'))
    )
    op.create_table('workspaces',
    sa.Column('id', sa.UUID(), nullable=False, comment='Global unique UUID for workspace'),
    sa.Column('name', sa.String(length=50), nullable=False, comment='Workspace name (Max 50 characters)'),
    sa.Column('description', sa.Text(), nullable=True, comment='Optional workspace description'),
    sa.Column('owner_id', sa.UUID(), nullable=False, comment='UUID of the workspace owner'),
    sa.Column('status', sa.String(length=20), nullable=False, comment='Workspace status (ACTIVE / SOFT_DELETED)'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Timestamp when the record was created'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Timestamp when the record was last updated'),
    sa.Column('is_deleted', sa.Boolean(), nullable=False, comment='Flag indicating soft deletion status'),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True, comment='Timestamp when the record was soft deleted'),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], name=op.f('fk_workspaces_owner_id_users'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_workspaces'))
    )
    op.create_index('ix_workspaces_is_deleted', 'workspaces', ['is_deleted'], unique=False)
    op.create_index('ix_workspaces_name', 'workspaces', ['name'], unique=False)
    op.create_index('ix_workspaces_owner_id', 'workspaces', ['owner_id'], unique=False)
    op.create_table('api_token_scopes',
    sa.Column('token_id', sa.UUID(), nullable=False),
    sa.Column('scope_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['scope_id'], ['api_scopes.id'], name=op.f('fk_api_token_scopes_scope_id_api_scopes')),
    sa.ForeignKeyConstraint(['token_id'], ['api_tokens.id'], name=op.f('fk_api_token_scopes_token_id_api_tokens')),
    sa.PrimaryKeyConstraint('token_id', 'scope_id', name=op.f('pk_api_token_scopes'))
    )
    op.create_table('integration_bindings',
    sa.Column('id', sa.UUID(), nullable=False, comment='Global unique UUID for integration binding'),
    sa.Column('workspace_id', sa.UUID(), nullable=False, comment='Reference to workspace'),
    sa.Column('created_by', sa.UUID(), nullable=False, comment='User who created the integration'),
    sa.Column('provider', sa.String(length=50), nullable=False, comment="Integration provider (e.g., 'slack', 'github', 'jira')"),
    sa.Column('name', sa.String(length=100), nullable=False, comment='Integration name/identifier'),
    sa.Column('is_active', sa.Boolean(), nullable=False, comment='Whether integration is active'),
    sa.Column('credentials', postgresql.JSONB(astext_type=sa.Text()), nullable=False, comment='Encrypted credentials/tokens (should be encrypted in app layer)'),
    sa.Column('config', postgresql.JSONB(astext_type=sa.Text()), nullable=False, comment='Integration-specific configuration'),
    sa.Column('status', sa.Enum('ACTIVE', 'INACTIVE', 'ERROR', name='integration_status'), nullable=False, comment='Integration status'),
    sa.Column('last_error', sa.Text(), nullable=True, comment='Last error message'),
    sa.Column('last_sync_at', sa.DateTime(timezone=True), nullable=True, comment='Timestamp of last successful sync'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Timestamp when the record was created'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Timestamp when the record was last updated'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_integration_bindings_created_by_users'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], name=op.f('fk_integration_bindings_workspace_id_workspaces'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_integration_bindings'))
    )
    op.create_index(op.f('ix_integration_bindings_is_active'), 'integration_bindings', ['is_active'], unique=False)
    op.create_index('ix_integration_bindings_provider', 'integration_bindings', ['provider'], unique=False)
    op.create_index(op.f('ix_integration_bindings_workspace_id'), 'integration_bindings', ['workspace_id'], unique=False)
    op.create_table('kpis',
    sa.Column('id', sa.UUID(), nullable=False, comment='Global unique UUID for KPI'),
    sa.Column('workspace_id', sa.UUID(), nullable=False, comment='Reference to workspace'),
    sa.Column('created_by', sa.UUID(), nullable=False, comment='User who created the KPI'),
    sa.Column('name', sa.String(length=100), nullable=False, comment='KPI name'),
    sa.Column('description', sa.Text(), nullable=True, comment='KPI description'),
    sa.Column('metric_key', sa.String(length=100), nullable=False, comment='Key to identify the underlying metric'),
    sa.Column('target_value', sa.Float(), nullable=False, comment='Target value for the KPI'),
    sa.Column('current_value', sa.Float(), nullable=True, comment='Current value of the KPI'),
    sa.Column('status', sa.Enum('ON_TRACK', 'AT_RISK', 'OFF_TRACK', name='kpi_status'), nullable=False, comment='KPI status based on current value vs target'),
    sa.Column('start_date', sa.DateTime(timezone=True), nullable=False, comment='KPI tracking start date'),
    sa.Column('end_date', sa.DateTime(timezone=True), nullable=False, comment='KPI tracking end date'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Timestamp when the record was created'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Timestamp when the record was last updated'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_kpis_created_by_users'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], name=op.f('fk_kpis_workspace_id_workspaces'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_kpis'))
    )
    op.create_index('ix_kpis_metric_key', 'kpis', ['metric_key'], unique=False)
    op.create_index(op.f('ix_kpis_workspace_id'), 'kpis', ['workspace_id'], unique=False)
    op.create_table('mfa_backup_codes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('mfa_id', sa.UUID(), nullable=False),
    sa.Column('code_hash', sa.String(length=255), nullable=False),
    sa.Column('used_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['mfa_id'], ['mfa_configs.id'], name=op.f('fk_mfa_backup_codes_mfa_id_mfa_configs')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_mfa_backup_codes'))
    )
    op.create_table('project_templates',
    sa.Column('id', sa.UUID(), nullable=False, comment='Primary key UUID for project template'),
    sa.Column('workspace_id', sa.UUID(), nullable=False, comment='Reference to workspace'),
    sa.Column('name', sa.String(length=100), nullable=False, comment='Template name'),
    sa.Column('description', sa.Text(), nullable=True, comment='Template description'),
    sa.Column('is_global', sa.Boolean(), nullable=False, comment='Whether template is globally available (admin only)'),
    sa.Column('config', postgresql.JSONB(astext_type=sa.Text()), nullable=False, comment='Template configuration (task lists, roles, etc.)'),
    sa.Column('created_by', sa.UUID(), nullable=True, comment='UUID of the user who created the record'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Timestamp when the record was created'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Timestamp when the record was last updated'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_project_templates_created_by_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], name=op.f('fk_project_templates_workspace_id_workspaces'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_project_templates'))
    )
    op.create_index('ix_project_templates_is_global', 'project_templates', ['is_global'], unique=False)
    op.create_index('ix_project_templates_workspace_id', 'project_templates', ['workspace_id'], unique=False)
    op.create_table('projects',
    sa.Column('id', sa.UUID(), nullable=False, comment='Global unique UUID for project'),
    sa.Column('workspace_id', sa.UUID(), nullable=False, comment='Reference to workspace'),
    sa.Column('owner_id', sa.UUID(), nullable=False, comment='UUID of the project owner'),
    sa.Column('name', sa.String(length=100), nullable=False, comment='Project name (Max 100 characters)'),
    sa.Column('description', sa.Text(), nullable=True, comment='Optional project description'),
    sa.Column('status', sa.Enum('NOT_STARTED', 'IN_PROGRESS', 'IN_REVIEW', 'DONE', 'CANCELLED', name='projectstatus'), nullable=False, comment='Project status (NOT_STARTED / IN_PROGRESS / IN_REVIEW / DONE / CANCELLED)'),
    sa.Column('governance_mode', sa.Enum('SIMPLE', 'STANDARD', 'STRICT', name='projectgovernancemode'), nullable=False, comment='Project governance mode (SIMPLE / STRICT)'),
    sa.Column('visibility', sa.Enum('PUBLIC', 'PRIVATE', name='projectvisibility'), nullable=False, comment='Project visibility (PUBLIC / PRIVATE)'),
    sa.Column('start_date', sa.Date(), nullable=True, comment='Project start date'),
    sa.Column('end_date', sa.Date(), nullable=True, comment='Project end date'),
    sa.Column('archived_at', sa.DateTime(timezone=True), nullable=True, comment='Timestamp when project was archived'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Timestamp when the record was created'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Timestamp when the record was last updated'),
    sa.Column('is_deleted', sa.Boolean(), nullable=False, comment='Flag indicating soft deletion status'),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True, comment='Timestamp when the record was soft deleted'),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], name=op.f('fk_projects_owner_id_users'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], name=op.f('fk_projects_workspace_id_workspaces'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_projects'))
    )
    op.create_index(op.f('ix_projects_is_deleted'), 'projects', ['is_deleted'], unique=False)
    op.create_index('ix_projects_name', 'projects', ['name'], unique=False)
    op.create_index('ix_projects_owner_id', 'projects', ['owner_id'], unique=False)
    op.create_index('ix_projects_status', 'projects', ['status'], unique=False)
    op.create_index('ix_projects_workspace_id', 'projects', ['workspace_id'], unique=False)
    op.create_table('report_definitions',
    sa.Column('id', sa.UUID(), nullable=False, comment='Global unique UUID for report definition'),
    sa.Column('workspace_id', sa.UUID(), nullable=False, comment='Reference to workspace'),
    sa.Column('created_by', sa.UUID(), nullable=False, comment='User who created the report'),
    sa.Column('name', sa.String(length=100), nullable=False, comment='Report name'),
    sa.Column('description', sa.Text(), nullable=True, comment='Report description'),
    sa.Column('report_type', sa.Enum('DASHBOARD', 'TABLE', 'CHART', 'EXPORT', name='report_type'), nullable=False, comment='Type of report'),
    sa.Column('filters', postgresql.JSONB(astext_type=sa.Text()), nullable=False, comment='Report filters and query parameters'),
    sa.Column('metrics', postgresql.JSONB(astext_type=sa.Text()), nullable=False, comment='Metrics to include in report'),
    sa.Column('visualization_config', postgresql.JSONB(astext_type=sa.Text()), nullable=False, comment='Visualization settings (colors, layout, etc.)'),
    sa.Column('is_scheduled', sa.Boolean(), nullable=False, comment='Whether report is scheduled for generation'),
    sa.Column('schedule_frequency', sa.Enum('DAILY', 'WEEKLY', 'MONTHLY', name='schedule_frequency'), nullable=True, comment='Report generation frequency (if scheduled)'),
    sa.Column('next_execution_at', sa.DateTime(timezone=True), nullable=True, comment='Next scheduled execution time'),
    sa.Column('is_public', sa.Boolean(), nullable=False, comment='Whether report is publicly accessible'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Timestamp when the record was created'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Timestamp when the record was last updated'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_report_definitions_created_by_users'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], name=op.f('fk_report_definitions_workspace_id_workspaces'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_report_definitions'))
    )
    op.create_index('ix_report_definitions_is_scheduled', 'report_definitions', ['is_scheduled'], unique=False)
    op.create_index(op.f('ix_report_definitions_workspace_id'), 'report_definitions', ['workspace_id'], unique=False)
    op.create_table('tags',
    sa.Column('id', sa.UUID(), nullable=False, comment='Global unique UUID for tag'),
    sa.Column('workspace_id', sa.UUID(), nullable=False, comment='Reference to workspace'),
    sa.Column('name', sa.String(length=50), nullable=False, comment='Tag name (Max 50 characters)'),
    sa.Column('color_code', sa.String(length=7), nullable=False, comment="Hex color code (e.g., '#FF5733')"),
    sa.Column('entity_type_limit', sa.Enum('TASK', 'PROJECT', 'ALL', name='tagentitytype'), nullable=False, comment='Entity type limit (TASK / PROJECT / ALL)'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Timestamp when the record was created'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Timestamp when the record was last updated'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], name=op.f('fk_tags_workspace_id_workspaces'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_tags'))
    )
    op.create_index(op.f('ix_tags_name'), 'tags', ['name'], unique=False)
    op.create_index('ix_tags_workspace_id', 'tags', ['workspace_id'], unique=False)
    op.create_table('webhook_endpoints',
    sa.Column('id', sa.UUID(), nullable=False, comment='Global unique UUID for webhook endpoint'),
    sa.Column('workspace_id', sa.UUID(), nullable=False, comment='Reference to workspace'),
    sa.Column('created_by', sa.UUID(), nullable=False, comment='User who created the webhook'),
    sa.Column('name', sa.String(length=100), nullable=False, comment='Webhook name'),
    sa.Column('url', sa.String(length=500), nullable=False, comment='Target URL to deliver events'),
    sa.Column('is_active', sa.Boolean(), nullable=False, comment='Whether webhook is active'),
    sa.Column('secret', sa.String(length=255), nullable=True, comment='Secret key for HMAC signature verification'),
    sa.Column('subscribed_events', postgresql.JSONB(astext_type=sa.Text()), nullable=False, comment="JSON object with subscribed event types as keys (e.g., {'task.created': true, 'task.updated': true})"),
    sa.Column('retry_policy', sa.Enum('EXPONENTIAL', 'LINEAR', 'NO_RETRY', name='retry_policy'), nullable=False, comment='Retry strategy for failed deliveries'),
    sa.Column('max_retries', sa.Integer(), nullable=False, comment='Maximum number of delivery retries'),
    sa.Column('timeout_seconds', sa.Integer(), nullable=False, comment='Request timeout in seconds'),
    sa.Column('last_triggered_at', sa.DateTime(timezone=True), nullable=True, comment='Timestamp of last event delivery'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Timestamp when the record was created'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Timestamp when the record was last updated'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_webhook_endpoints_created_by_users'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], name=op.f('fk_webhook_endpoints_workspace_id_workspaces'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_webhook_endpoints'))
    )
    op.create_index(op.f('ix_webhook_endpoints_is_active'), 'webhook_endpoints', ['is_active'], unique=False)
    op.create_index('ix_webhook_endpoints_workspace_id', 'webhook_endpoints', ['workspace_id'], unique=False)
    op.create_table('workspace_access_logs',
    sa.Column('id', sa.UUID(), nullable=False, comment='Primary key UUID for access log'),
    sa.Column('user_id', sa.UUID(), nullable=False, comment='Reference to user'),
    sa.Column('workspace_id', sa.UUID(), nullable=False, comment='Reference to workspace'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Timestamp when the record was created'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Timestamp when the record was last updated'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_workspace_access_logs_user_id_users'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], name=op.f('fk_workspace_access_logs_workspace_id_workspaces'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_workspace_access_logs'))
    )
    op.create_index('ix_workspace_access_logs_created_at', 'workspace_access_logs', ['created_at'], unique=False)
    op.create_index('ix_workspace_access_logs_user_id', 'workspace_access_logs', ['user_id'], unique=False)
    op.create_index('ix_workspace_access_logs_workspace_id', 'workspace_access_logs', ['workspace_id'], unique=False)
    op.create_table('workspace_invitations',
    sa.Column('id', sa.UUID(), nullable=False, comment='Primary key UUID for invitation'),
    sa.Column('workspace_id', sa.UUID(), nullable=False, comment='Reference to workspace being invited to'),
    sa.Column('invited_by', sa.UUID(), nullable=True, comment='UUID of user who sent the invitation'),
    sa.Column('email', sa.String(length=255), nullable=False, comment='Email address of invited user'),
    sa.Column('invited_role', sa.Enum('OWNER', 'ADMIN', 'MEMBER', 'VIEWER', 'GUEST', name='workspacerole'), nullable=False, comment='Role to be assigned (ADMIN / MEMBER / VIEWER)'),
    sa.Column('token_hash', sa.String(length=255), nullable=False, comment='Hash of invitation token for security'),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False, comment='Expiration timestamp (+48h from creation)'),
    sa.Column('accepted_at', sa.DateTime(timezone=True), nullable=True, comment='Timestamp when invitation was accepted (nullable)'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Timestamp when the record was created'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Timestamp when the record was last updated'),
    sa.ForeignKeyConstraint(['invited_by'], ['users.id'], name=op.f('fk_workspace_invitations_invited_by_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], name=op.f('fk_workspace_invitations_workspace_id_workspaces'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_workspace_invitations'))
    )
    op.create_index('ix_workspace_invitations_email', 'workspace_invitations', ['email'], unique=False)
    op.create_index('ix_workspace_invitations_token_hash', 'workspace_invitations', ['token_hash'], unique=False)
    op.create_index('ix_workspace_invitations_workspace_id', 'workspace_invitations', ['workspace_id'], unique=False)
    op.create_table('workspace_members',
    sa.Column('id', sa.UUID(), nullable=False, comment='Primary key UUID for workspace member'),
    sa.Column('workspace_id', sa.UUID(), nullable=False, comment='Reference to workspace'),
    sa.Column('user_id', sa.UUID(), nullable=False, comment='Reference to user'),
    sa.Column('role', sa.Enum('OWNER', 'ADMIN', 'MEMBER', 'VIEWER', 'GUEST', name='workspacerole'), nullable=False, comment='Role within workspace (OWNER / ADMIN / MEMBER / VIEWER / GUEST)'),
    sa.Column('is_active', sa.Boolean(), nullable=False, comment='Whether member is active in workspace'),
    sa.Column('left_at', sa.DateTime(timezone=True), nullable=True, comment='Timestamp when member left workspace (nullable)'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Timestamp when the record was created'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Timestamp when the record was last updated'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_workspace_members_user_id_users'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], name=op.f('fk_workspace_members_workspace_id_workspaces'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_workspace_members'))
    )
    op.create_index(op.f('ix_workspace_members_is_active'), 'workspace_members', ['is_active'], unique=False)
    op.create_index('ix_workspace_members_user_id', 'workspace_members', ['user_id'], unique=False)
    op.create_index('ix_workspace_members_workspace_id', 'workspace_members', ['workspace_id'], unique=False)
    op.create_index('ix_workspace_members_workspace_user', 'workspace_members', ['workspace_id', 'user_id'], unique=True)
    op.create_table('workspace_members_association',
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_workspace_members_association_user_id_users')),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], name=op.f('fk_workspace_members_association_workspace_id_workspaces')),
    sa.PrimaryKeyConstraint('workspace_id', 'user_id', name=op.f('pk_workspace_members_association'))
    )
    op.create_table('workspace_settings',
    sa.Column('workspace_id', sa.UUID(), nullable=False, comment='Reference to workspace (PK and FK)'),
    sa.Column('timezone', sa.String(length=50), nullable=True, comment="Workspace timezone (e.g., 'UTC', 'Asia/Ho_Chi_Minh')"),
    sa.Column('work_days', sa.String(length=255), nullable=True, comment="Working days (e.g., 'Mon,Tue,Wed,Thu,Fri')"),
    sa.Column('work_hours', sa.String(length=255), nullable=True, comment="Working hours (e.g., '{start: 09:00, end: 18:00}')"),
    sa.Column('logo_url', sa.String(length=500), nullable=True, comment='URL to workspace logo'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Timestamp when the record was created'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Timestamp when the record was last updated'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], name=op.f('fk_workspace_settings_workspace_id_workspaces'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('workspace_id', name=op.f('pk_workspace_settings'))
    )
    op.create_table('metric_snapshots',
    sa.Column('id', sa.UUID(), nullable=False, comment='Global unique UUID for metric snapshot'),
    sa.Column('workspace_id', sa.UUID(), nullable=False, comment='Reference to workspace'),
    sa.Column('project_id', sa.UUID(), nullable=True, comment='Optional reference to project (if project-specific)'),
    sa.Column('metric_name', sa.String(length=100), nullable=False, comment="Name of the metric (e.g., 'tasks_completed', 'velocity')"),
    sa.Column('metric_value', sa.Float(), nullable=False, comment='Numeric value of the metric'),
    sa.Column('meta', postgresql.JSONB(astext_type=sa.Text()), nullable=False, comment='Additional metric metadata'),
    sa.Column('period_start', sa.DateTime(timezone=True), nullable=False, comment='Start of measurement period'),
    sa.Column('period_end', sa.DateTime(timezone=True), nullable=False, comment='End of measurement period'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Timestamp when the record was created'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Timestamp when the record was last updated'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('fk_metric_snapshots_project_id_projects'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], name=op.f('fk_metric_snapshots_workspace_id_workspaces'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_metric_snapshots'))
    )
    op.create_index('ix_metric_snapshots_metric_name', 'metric_snapshots', ['metric_name'], unique=False)
    op.create_index('ix_metric_snapshots_period_start', 'metric_snapshots', ['period_start'], unique=False)
    op.create_index(op.f('ix_metric_snapshots_workspace_id'), 'metric_snapshots', ['workspace_id'], unique=False)
    op.create_table('project_archives',
    sa.Column('id', sa.UUID(), nullable=False, comment='Primary key UUID for project archive'),
    sa.Column('project_id', sa.UUID(), nullable=False, comment='Reference to archived project'),
    sa.Column('reason', sa.Text(), nullable=True, comment='Reason for archival'),
    sa.Column('archive_location', sa.String(length=500), nullable=True, comment='Storage location of archived data'),
    sa.Column('created_by', sa.UUID(), nullable=True, comment='UUID of the user who created the record'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Timestamp when the record was created'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Timestamp when the record was last updated'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_project_archives_created_by_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('fk_project_archives_project_id_projects'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_project_archives')),
    sa.UniqueConstraint('project_id', name=op.f('uq_project_archives_project_id'))
    )
    op.create_index('ix_project_archives_project_id', 'project_archives', ['project_id'], unique=False)
    op.create_table('project_baselines',
    sa.Column('id', sa.UUID(), nullable=False, comment='Primary key UUID for project baseline'),
    sa.Column('project_id', sa.UUID(), nullable=False, comment='Reference to project'),
    sa.Column('version', sa.Integer(), nullable=False, comment='Baseline version number'),
    sa.Column('snapshot_ref', sa.String(length=255), nullable=False, comment='Reference to snapshot (file path, commit hash, etc.)'),
    sa.Column('is_active', sa.Boolean(), nullable=False, comment='Whether this is the current active baseline'),
    sa.Column('snapshot_data', postgresql.JSONB(astext_type=sa.Text()), nullable=False, comment='Snapshot of project state at baseline creation'),
    sa.Column('created_by', sa.UUID(), nullable=True, comment='UUID of the user who created the record'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Timestamp when the record was created'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Timestamp when the record was last updated'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_project_baselines_created_by_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('fk_project_baselines_project_id_projects'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_project_baselines'))
    )
    op.create_index('ix_project_baselines_is_active', 'project_baselines', ['is_active'], unique=False)
    op.create_index('ix_project_baselines_project_id', 'project_baselines', ['project_id'], unique=False)
    op.create_table('project_change_requests',
    sa.Column('id', sa.UUID(), nullable=False, comment='Primary key UUID for change request'),
    sa.Column('project_id', sa.UUID(), nullable=False, comment='Reference to project'),
    sa.Column('title', sa.String(length=255), nullable=False, comment='Change request title'),
    sa.Column('description', sa.Text(), nullable=True, comment='Detailed description of the change'),
    sa.Column('status', sa.Enum('PENDING', 'APPROVED', 'REJECTED', 'IMPLEMENTED', name='change_request_status'), nullable=False, comment='Change request status'),
    sa.Column('impact_assessment', sa.Text(), nullable=True, comment='Assessment of change impact'),
    sa.Column('approved_by', sa.UUID(), nullable=True, comment='User who approved the change'),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True, comment='Timestamp of approval'),
    sa.Column('created_by', sa.UUID(), nullable=True, comment='UUID of the user who created the record'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Timestamp when the record was created'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Timestamp when the record was last updated'),
    sa.ForeignKeyConstraint(['approved_by'], ['users.id'], name=op.f('fk_project_change_requests_approved_by_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_project_change_requests_created_by_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('fk_project_change_requests_project_id_projects'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_project_change_requests'))
    )
    op.create_index('ix_project_change_requests_project_id', 'project_change_requests', ['project_id'], unique=False)
    op.create_index('ix_project_change_requests_status', 'project_change_requests', ['status'], unique=False)
    op.create_table('project_members',
    sa.Column('id', sa.UUID(), nullable=False, comment='Primary key UUID for project member'),
    sa.Column('project_id', sa.UUID(), nullable=False, comment='Reference to project'),
    sa.Column('user_id', sa.UUID(), nullable=False, comment='Reference to user'),
    sa.Column('role', sa.String(length=50), nullable=False, comment='Project-level role (e.g., LEAD, MEMBER, VIEWER)'),
    sa.Column('joined_at', sa.DateTime(timezone=True), nullable=False, comment='Timestamp when user joined project'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Timestamp when the record was created'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Timestamp when the record was last updated'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('fk_project_members_project_id_projects'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_project_members_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_project_members'))
    )
    op.create_index('ix_project_members_project_id', 'project_members', ['project_id'], unique=False)
    op.create_index('ix_project_members_project_user', 'project_members', ['project_id', 'user_id'], unique=True)
    op.create_index('ix_project_members_user_id', 'project_members', ['user_id'], unique=False)
    op.create_table('project_members_association',
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('fk_project_members_association_project_id_projects')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_project_members_association_user_id_users')),
    sa.PrimaryKeyConstraint('project_id', 'user_id', name=op.f('pk_project_members_association'))
    )
    op.create_table('project_tag_map',
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('tag_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('fk_project_tag_map_project_id_projects')),
    sa.ForeignKeyConstraint(['tag_id'], ['tags.id'], name=op.f('fk_project_tag_map_tag_id_tags')),
    sa.PrimaryKeyConstraint('project_id', 'tag_id', name=op.f('pk_project_tag_map'))
    )
    op.create_table('project_template_members_association',
    sa.Column('template_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['template_id'], ['project_templates.id'], name=op.f('fk_project_template_members_association_template_id_project_templates')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_project_template_members_association_user_id_users')),
    sa.PrimaryKeyConstraint('template_id', 'user_id', name=op.f('pk_project_template_members_association'))
    )
    op.create_table('report_executions',
    sa.Column('id', sa.UUID(), nullable=False, comment='Global unique UUID for report execution'),
    sa.Column('report_id', sa.UUID(), nullable=False, comment='Reference to report definition'),
    sa.Column('triggered_by', sa.UUID(), nullable=False, comment='User who triggered the report execution'),
    sa.Column('status', sa.Enum('PENDING', 'PROCESSING', 'COMPLETED', 'FAILED', name='execution_status'), nullable=False, comment='Execution status'),
    sa.Column('result_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='Generated report data (JSON)'),
    sa.Column('execution_time_ms', sa.Integer(), nullable=True, comment='Execution time in milliseconds'),
    sa.Column('error_message', sa.Text(), nullable=True, comment='Error message if execution failed'),
    sa.Column('export_format', sa.Enum('PDF', 'EXCEL', 'CSV', 'JSON', name='export_format'), nullable=True, comment='Export format if applicable'),
    sa.Column('export_file_path', sa.String(length=500), nullable=True, comment='Path to exported file'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Timestamp when the record was created'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Timestamp when the record was last updated'),
    sa.ForeignKeyConstraint(['report_id'], ['report_definitions.id'], name=op.f('fk_report_executions_report_id_report_definitions'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['triggered_by'], ['users.id'], name=op.f('fk_report_executions_triggered_by_users'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_report_executions'))
    )
    op.create_index('ix_report_executions_created_at', 'report_executions', ['created_at'], unique=False)
    op.create_index(op.f('ix_report_executions_report_id'), 'report_executions', ['report_id'], unique=False)
    op.create_index(op.f('ix_report_executions_status'), 'report_executions', ['status'], unique=False)
    op.create_table('task_lists',
    sa.Column('id', sa.UUID(), nullable=False, comment='Global unique UUID for task list'),
    sa.Column('project_id', sa.UUID(), nullable=False, comment='Reference to project'),
    sa.Column('name', sa.String(length=100), nullable=False, comment='Task list name'),
    sa.Column('position', sa.Integer(), nullable=False, comment='Position for drag & drop ordering'),
    sa.Column('is_archived', sa.Boolean(), nullable=False, comment='Whether task list is archived'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Timestamp when the record was created'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Timestamp when the record was last updated'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('fk_task_lists_project_id_projects'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_task_lists'))
    )
    op.create_index('ix_task_lists_is_archived', 'task_lists', ['is_archived'], unique=False)
    op.create_index(op.f('ix_task_lists_name'), 'task_lists', ['name'], unique=False)
    op.create_index('ix_task_lists_position', 'task_lists', ['position'], unique=False)
    op.create_index('ix_task_lists_project_id', 'task_lists', ['project_id'], unique=False)
    op.create_table('webhook_deliveries',
    sa.Column('id', sa.UUID(), nullable=False, comment='Global unique UUID for webhook delivery'),
    sa.Column('endpoint_id', sa.UUID(), nullable=False, comment='Reference to webhook endpoint'),
    sa.Column('event_id', sa.UUID(), nullable=False, comment='Reference to webhook event type'),
    sa.Column('domain_event_id', sa.UUID(), nullable=True, comment='Reference to domain event that triggered delivery'),
    sa.Column('status', sa.Enum('PENDING', 'DELIVERED', 'FAILED', 'RETRYING', name='webhook_delivery_status'), nullable=False, comment='Delivery status'),
    sa.Column('attempt_count', sa.Integer(), nullable=False, comment='Number of delivery attempts'),
    sa.Column('response_status_code', sa.Integer(), nullable=True, comment='HTTP response status code'),
    sa.Column('response_body', sa.Text(), nullable=True, comment='HTTP response body (truncated)'),
    sa.Column('error_message', sa.Text(), nullable=True, comment='Error message if delivery failed'),
    sa.Column('next_retry_at', sa.DateTime(timezone=True), nullable=True, comment='Scheduled time for next retry'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Timestamp when the record was created'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Timestamp when the record was last updated'),
    sa.ForeignKeyConstraint(['domain_event_id'], ['domain_events.id'], name=op.f('fk_webhook_deliveries_domain_event_id_domain_events'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['endpoint_id'], ['webhook_endpoints.id'], name=op.f('fk_webhook_deliveries_endpoint_id_webhook_endpoints'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['event_id'], ['webhook_events.id'], name=op.f('fk_webhook_deliveries_event_id_webhook_events'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_webhook_deliveries'))
    )
    op.create_index('ix_webhook_deliveries_created_at', 'webhook_deliveries', ['created_at'], unique=False)
    op.create_index('ix_webhook_deliveries_endpoint_id', 'webhook_deliveries', ['endpoint_id'], unique=False)
    op.create_index(op.f('ix_webhook_deliveries_event_id'), 'webhook_deliveries', ['event_id'], unique=False)
    op.create_index(op.f('ix_webhook_deliveries_status'), 'webhook_deliveries', ['status'], unique=False)
    op.create_table('tasks',
    sa.Column('id', sa.UUID(), nullable=False, comment='Global unique UUID for task'),
    sa.Column('project_id', sa.UUID(), nullable=False, comment='Reference to project'),
    sa.Column('task_list_id', sa.UUID(), nullable=False, comment='Reference to task list'),
    sa.Column('created_by', sa.UUID(), nullable=False, comment='User who created the task'),
    sa.Column('title', sa.String(length=255), nullable=False, comment='Task title'),
    sa.Column('description', sa.Text(), nullable=True, comment='Task description (rich-text or markdown)'),
    sa.Column('status', sa.Enum('BACKLOG', 'TO_DO', 'IN_PROGRESS', 'IN_REVIEW', 'DONE', 'CANCELLED', name='taskstatus'), nullable=False, comment='Task status'),
    sa.Column('priority', sa.Enum('LOW', 'MEDIUM', 'HIGH', 'CRITICAL', name='taskpriority'), nullable=False, comment='Task priority level'),
    sa.Column('is_milestone', sa.Boolean(), nullable=False, comment='Whether this task is a milestone'),
    sa.Column('planned_start', sa.DateTime(timezone=True), nullable=True, comment='Planned start date/time'),
    sa.Column('planned_end', sa.DateTime(timezone=True), nullable=True, comment='Planned end date/time'),
    sa.Column('actual_start', sa.DateTime(timezone=True), nullable=True, comment='Auto-set when task moves to IN_PROGRESS'),
    sa.Column('actual_end', sa.DateTime(timezone=True), nullable=True, comment='Auto-set when task moves to DONE'),
    sa.Column('estimated_hours', sa.Float(), nullable=True, comment='Estimated hours to complete task'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Timestamp when the record was created'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Timestamp when the record was last updated'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_tasks_created_by_users'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('fk_tasks_project_id_projects'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['task_list_id'], ['task_lists.id'], name=op.f('fk_tasks_task_list_id_task_lists'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_tasks'))
    )
    op.create_index('ix_tasks_created_by', 'tasks', ['created_by'], unique=False)
    op.create_index('ix_tasks_priority', 'tasks', ['priority'], unique=False)
    op.create_index('ix_tasks_project_id', 'tasks', ['project_id'], unique=False)
    op.create_index('ix_tasks_status', 'tasks', ['status'], unique=False)
    op.create_index('ix_tasks_task_list_id', 'tasks', ['task_list_id'], unique=False)
    op.create_index(op.f('ix_tasks_title'), 'tasks', ['title'], unique=False)
    op.create_table('comments',
    sa.Column('id', sa.UUID(), nullable=False, comment='Global unique UUID for comment'),
    sa.Column('task_id', sa.UUID(), nullable=False, comment='Reference to task (context)'),
    sa.Column('author_id', sa.UUID(), nullable=False, comment='User who wrote the comment'),
    sa.Column('parent_comment_id', sa.UUID(), nullable=True, comment='Parent comment for nested replies (NULL = root)'),
    sa.Column('content', sa.Text(), nullable=False, comment='Comment content (rich-text HTML/JSON)'),
    sa.Column('is_edited', sa.Boolean(), nullable=False, comment='Whether comment has been edited'),
    sa.Column('edited_at', sa.DateTime(timezone=True), nullable=True, comment='Timestamp of last edit'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Timestamp when the record was created'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Timestamp when the record was last updated'),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], name=op.f('fk_comments_author_id_users'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['parent_comment_id'], ['comments.id'], name=op.f('fk_comments_parent_comment_id_comments'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], name=op.f('fk_comments_task_id_tasks'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_comments'))
    )
    op.create_index('ix_comments_author_id', 'comments', ['author_id'], unique=False)
    op.create_index('ix_comments_parent_comment_id', 'comments', ['parent_comment_id'], unique=False)
    op.create_index('ix_comments_task_id', 'comments', ['task_id'], unique=False)
    op.create_table('files',
    sa.Column('id', sa.UUID(), nullable=False, comment='Global unique UUID for file'),
    sa.Column('task_id', sa.UUID(), nullable=False, comment='Reference to task (context)'),
    sa.Column('uploaded_by', sa.UUID(), nullable=False, comment='User who uploaded the file'),
    sa.Column('filename', sa.String(length=255), nullable=False, comment='Original filename'),
    sa.Column('mime_type', sa.String(length=100), nullable=False, comment='MIME type (e.g., image/png)'),
    sa.Column('size', sa.Integer(), nullable=False, comment='File size in bytes'),
    sa.Column('current_version', sa.Integer(), nullable=False, comment='Current version number'),
    sa.Column('storage_tier', sa.Enum('HOT', 'COLD', name='storage_tier'), nullable=False, comment='Storage tier (HOT = frequently accessed, COLD = archived)'),
    sa.Column('storage_path', sa.String(length=500), nullable=False, comment='Path to file in storage (S3, local, etc.)'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Timestamp when the record was created'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Timestamp when the record was last updated'),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], name=op.f('fk_files_task_id_tasks'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['uploaded_by'], ['users.id'], name=op.f('fk_files_uploaded_by_users'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_files'))
    )
    op.create_index(op.f('ix_files_task_id'), 'files', ['task_id'], unique=False)
    op.create_index('ix_files_uploaded_by', 'files', ['uploaded_by'], unique=False)
    op.create_table('subtasks',
    sa.Column('id', sa.UUID(), nullable=False, comment='Global unique UUID for subtask'),
    sa.Column('task_id', sa.UUID(), nullable=False, comment='Reference to parent task'),
    sa.Column('assignee_id', sa.UUID(), nullable=True, comment='Optional assignee for subtask'),
    sa.Column('title', sa.String(length=255), nullable=False, comment='Subtask title'),
    sa.Column('is_done', sa.Boolean(), nullable=False, comment='Whether subtask is completed'),
    sa.Column('position', sa.Integer(), nullable=False, comment='Position for ordering'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Timestamp when the record was created'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Timestamp when the record was last updated'),
    sa.ForeignKeyConstraint(['assignee_id'], ['users.id'], name=op.f('fk_subtasks_assignee_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], name=op.f('fk_subtasks_task_id_tasks'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_subtasks'))
    )
    op.create_index('ix_subtasks_assignee_id', 'subtasks', ['assignee_id'], unique=False)
    op.create_index('ix_subtasks_position', 'subtasks', ['position'], unique=False)
    op.create_index('ix_subtasks_task_id', 'subtasks', ['task_id'], unique=False)
    op.create_table('task_assignees',
    sa.Column('id', sa.UUID(), nullable=False, comment='Global unique UUID for task assignee'),
    sa.Column('task_id', sa.UUID(), nullable=False, comment='Reference to task'),
    sa.Column('user_id', sa.UUID(), nullable=False, comment='Reference to user'),
    sa.Column('is_primary', sa.Boolean(), nullable=False, comment='Whether this is the primary assignee'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Timestamp when the record was created'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Timestamp when the record was last updated'),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], name=op.f('fk_task_assignees_task_id_tasks'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_task_assignees_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_task_assignees'))
    )
    op.create_index('ix_task_assignees_is_primary', 'task_assignees', ['is_primary'], unique=False)
    op.create_index('ix_task_assignees_task_id', 'task_assignees', ['task_id'], unique=False)
    op.create_index('ix_task_assignees_user_id', 'task_assignees', ['user_id'], unique=False)
    op.create_table('task_assignees_association',
    sa.Column('task_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], name=op.f('fk_task_assignees_association_task_id_tasks')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_task_assignees_association_user_id_users')),
    sa.PrimaryKeyConstraint('task_id', 'user_id', name=op.f('pk_task_assignees_association'))
    )
    op.create_table('task_dependencies',
    sa.Column('id', sa.UUID(), nullable=False, comment='Global unique UUID for task dependency'),
    sa.Column('task_id', sa.UUID(), nullable=False, comment='Task that has the dependency'),
    sa.Column('depends_on_task_id', sa.UUID(), nullable=False, comment='Task that must be completed first'),
    sa.Column('dependency_type', sa.Enum('BLOCKS', 'BLOCKED_BY', 'RELATED_TO', 'DUPLICATES', name='dependency_type'), nullable=False, comment='Type of dependency relationship'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Timestamp when the record was created'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Timestamp when the record was last updated'),
    sa.ForeignKeyConstraint(['depends_on_task_id'], ['tasks.id'], name=op.f('fk_task_dependencies_depends_on_task_id_tasks'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], name=op.f('fk_task_dependencies_task_id_tasks'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_task_dependencies'))
    )
    op.create_index(op.f('ix_task_dependencies_depends_on_task_id'), 'task_dependencies', ['depends_on_task_id'], unique=False)
    op.create_index(op.f('ix_task_dependencies_task_id'), 'task_dependencies', ['task_id'], unique=False)
    op.create_table('task_tag_map',
    sa.Column('task_id', sa.UUID(), nullable=False),
    sa.Column('tag_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['tag_id'], ['tags.id'], name=op.f('fk_task_tag_map_tag_id_tags')),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], name=op.f('fk_task_tag_map_task_id_tasks')),
    sa.PrimaryKeyConstraint('task_id', 'tag_id', name=op.f('pk_task_tag_map'))
    )
    op.create_table('task_watchers_association',
    sa.Column('task_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], name=op.f('fk_task_watchers_association_task_id_tasks')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_task_watchers_association_user_id_users')),
    sa.PrimaryKeyConstraint('task_id', 'user_id', name=op.f('pk_task_watchers_association'))
    )
    op.create_table('time_entries',
    sa.Column('id', sa.UUID(), nullable=False, comment='Global unique UUID for time entry'),
    sa.Column('task_id', sa.UUID(), nullable=False, comment='Reference to task'),
    sa.Column('user_id', sa.UUID(), nullable=False, comment='User who logged the time'),
    sa.Column('hours_spent', sa.Float(), nullable=False, comment='Hours spent on this task'),
    sa.Column('date_logged', sa.DateTime(timezone=True), nullable=False, comment='Date when time was logged'),
    sa.Column('description', sa.Text(), nullable=True, comment='Optional description of work done'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Timestamp when the record was created'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Timestamp when the record was last updated'),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], name=op.f('fk_time_entries_task_id_tasks'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_time_entries_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_time_entries'))
    )
    op.create_index('ix_time_entries_date_logged', 'time_entries', ['date_logged'], unique=False)
    op.create_index(op.f('ix_time_entries_task_id'), 'time_entries', ['task_id'], unique=False)
    op.create_index('ix_time_entries_user_id', 'time_entries', ['user_id'], unique=False)
    op.create_table('file_versions',
    sa.Column('id', sa.UUID(), nullable=False, comment='Global unique UUID for file version'),
    sa.Column('file_id', sa.UUID(), nullable=False, comment='Reference to file'),
    sa.Column('version_number', sa.Integer(), nullable=False, comment='Version number'),
    sa.Column('storage_path', sa.String(length=500), nullable=False, comment='Path to this version in storage'),
    sa.Column('size', sa.Integer(), nullable=False, comment='File size of this version'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Timestamp when the record was created'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Timestamp when the record was last updated'),
    sa.ForeignKeyConstraint(['file_id'], ['files.id'], name=op.f('fk_file_versions_file_id_files'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_file_versions'))
    )
    op.create_index(op.f('ix_file_versions_file_id'), 'file_versions', ['file_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_file_versions_file_id'), table_name='file_versions')
    op.drop_table('file_versions')
    op.drop_index('ix_time_entries_user_id', table_name='time_entries')
    op.drop_index(op.f('ix_time_entries_task_id'), table_name='time_entries')
    op.drop_index('ix_time_entries_date_logged', table_name='time_entries')
    op.drop_table('time_entries')
    op.drop_table('task_watchers_association')
    op.drop_table('task_tag_map')
    op.drop_index(op.f('ix_task_dependencies_task_id'), table_name='task_dependencies')
    op.drop_index(op.f('ix_task_dependencies_depends_on_task_id'), table_name='task_dependencies')
    op.drop_table('task_dependencies')
    op.drop_table('task_assignees_association')
    op.drop_index('ix_task_assignees_user_id', table_name='task_assignees')
    op.drop_index('ix_task_assignees_task_id', table_name='task_assignees')
    op.drop_index('ix_task_assignees_is_primary', table_name='task_assignees')
    op.drop_table('task_assignees')
    op.drop_index('ix_subtasks_task_id', table_name='subtasks')
    op.drop_index('ix_subtasks_position', table_name='subtasks')
    op.drop_index('ix_subtasks_assignee_id', table_name='subtasks')
    op.drop_table('subtasks')
    op.drop_index('ix_files_uploaded_by', table_name='files')
    op.drop_index(op.f('ix_files_task_id'), table_name='files')
    op.drop_table('files')
    op.drop_index('ix_comments_task_id', table_name='comments')
    op.drop_index('ix_comments_parent_comment_id', table_name='comments')
    op.drop_index('ix_comments_author_id', table_name='comments')
    op.drop_table('comments')
    op.drop_index(op.f('ix_tasks_title'), table_name='tasks')
    op.drop_index('ix_tasks_task_list_id', table_name='tasks')
    op.drop_index('ix_tasks_status', table_name='tasks')
    op.drop_index('ix_tasks_project_id', table_name='tasks')
    op.drop_index('ix_tasks_priority', table_name='tasks')
    op.drop_index('ix_tasks_created_by', table_name='tasks')
    op.drop_table('tasks')
    op.drop_index(op.f('ix_webhook_deliveries_status'), table_name='webhook_deliveries')
    op.drop_index(op.f('ix_webhook_deliveries_event_id'), table_name='webhook_deliveries')
    op.drop_index('ix_webhook_deliveries_endpoint_id', table_name='webhook_deliveries')
    op.drop_index('ix_webhook_deliveries_created_at', table_name='webhook_deliveries')
    op.drop_table('webhook_deliveries')
    op.drop_index('ix_task_lists_project_id', table_name='task_lists')
    op.drop_index('ix_task_lists_position', table_name='task_lists')
    op.drop_index(op.f('ix_task_lists_name'), table_name='task_lists')
    op.drop_index('ix_task_lists_is_archived', table_name='task_lists')
    op.drop_table('task_lists')
    op.drop_index(op.f('ix_report_executions_status'), table_name='report_executions')
    op.drop_index(op.f('ix_report_executions_report_id'), table_name='report_executions')
    op.drop_index('ix_report_executions_created_at', table_name='report_executions')
    op.drop_table('report_executions')
    op.drop_table('project_template_members_association')
    op.drop_table('project_tag_map')
    op.drop_table('project_members_association')
    op.drop_index('ix_project_members_user_id', table_name='project_members')
    op.drop_index('ix_project_members_project_user', table_name='project_members')
    op.drop_index('ix_project_members_project_id', table_name='project_members')
    op.drop_table('project_members')
    op.drop_index('ix_project_change_requests_status', table_name='project_change_requests')
    op.drop_index('ix_project_change_requests_project_id', table_name='project_change_requests')
    op.drop_table('project_change_requests')
    op.drop_index('ix_project_baselines_project_id', table_name='project_baselines')
    op.drop_index('ix_project_baselines_is_active', table_name='project_baselines')
    op.drop_table('project_baselines')
    op.drop_index('ix_project_archives_project_id', table_name='project_archives')
    op.drop_table('project_archives')
    op.drop_index(op.f('ix_metric_snapshots_workspace_id'), table_name='metric_snapshots')
    op.drop_index('ix_metric_snapshots_period_start', table_name='metric_snapshots')
    op.drop_index('ix_metric_snapshots_metric_name', table_name='metric_snapshots')
    op.drop_table('metric_snapshots')
    op.drop_table('workspace_settings')
    op.drop_table('workspace_members_association')
    op.drop_index('ix_workspace_members_workspace_user', table_name='workspace_members')
    op.drop_index('ix_workspace_members_workspace_id', table_name='workspace_members')
    op.drop_index('ix_workspace_members_user_id', table_name='workspace_members')
    op.drop_index(op.f('ix_workspace_members_is_active'), table_name='workspace_members')
    op.drop_table('workspace_members')
    op.drop_index('ix_workspace_invitations_workspace_id', table_name='workspace_invitations')
    op.drop_index('ix_workspace_invitations_token_hash', table_name='workspace_invitations')
    op.drop_index('ix_workspace_invitations_email', table_name='workspace_invitations')
    op.drop_table('workspace_invitations')
    op.drop_index('ix_workspace_access_logs_workspace_id', table_name='workspace_access_logs')
    op.drop_index('ix_workspace_access_logs_user_id', table_name='workspace_access_logs')
    op.drop_index('ix_workspace_access_logs_created_at', table_name='workspace_access_logs')
    op.drop_table('workspace_access_logs')
    op.drop_index('ix_webhook_endpoints_workspace_id', table_name='webhook_endpoints')
    op.drop_index(op.f('ix_webhook_endpoints_is_active'), table_name='webhook_endpoints')
    op.drop_table('webhook_endpoints')
    op.drop_index('ix_tags_workspace_id', table_name='tags')
    op.drop_index(op.f('ix_tags_name'), table_name='tags')
    op.drop_table('tags')
    op.drop_index(op.f('ix_report_definitions_workspace_id'), table_name='report_definitions')
    op.drop_index('ix_report_definitions_is_scheduled', table_name='report_definitions')
    op.drop_table('report_definitions')
    op.drop_index('ix_projects_workspace_id', table_name='projects')
    op.drop_index('ix_projects_status', table_name='projects')
    op.drop_index('ix_projects_owner_id', table_name='projects')
    op.drop_index('ix_projects_name', table_name='projects')
    op.drop_index(op.f('ix_projects_is_deleted'), table_name='projects')
    op.drop_table('projects')
    op.drop_index('ix_project_templates_workspace_id', table_name='project_templates')
    op.drop_index('ix_project_templates_is_global', table_name='project_templates')
    op.drop_table('project_templates')
    op.drop_table('mfa_backup_codes')
    op.drop_index(op.f('ix_kpis_workspace_id'), table_name='kpis')
    op.drop_index('ix_kpis_metric_key', table_name='kpis')
    op.drop_table('kpis')
    op.drop_index(op.f('ix_integration_bindings_workspace_id'), table_name='integration_bindings')
    op.drop_index('ix_integration_bindings_provider', table_name='integration_bindings')
    op.drop_index(op.f('ix_integration_bindings_is_active'), table_name='integration_bindings')
    op.drop_table('integration_bindings')
    op.drop_table('api_token_scopes')
    op.drop_index('ix_workspaces_owner_id', table_name='workspaces')
    op.drop_index('ix_workspaces_name', table_name='workspaces')
    op.drop_index('ix_workspaces_is_deleted', table_name='workspaces')
    op.drop_table('workspaces')
    op.drop_table('user_roles')
    op.drop_index(op.f('ix_timesheets_user_id'), table_name='timesheets')
    op.drop_index('ix_timesheets_status', table_name='timesheets')
    op.drop_index('ix_timesheets_period_start', table_name='timesheets')
    op.drop_index('ix_timesheets_period_end', table_name='timesheets')
    op.drop_table('timesheets')
    op.drop_table('sessions')
    op.drop_table('role_permissions')
    op.drop_index(op.f('ix_notifications_user_id'), table_name='notifications')
    op.drop_index('ix_notifications_is_read', table_name='notifications')
    op.drop_index('ix_notifications_created_at', table_name='notifications')
    op.drop_table('notifications')
    op.drop_table('notification_preferences')
    op.drop_table('mfa_configs')
    op.drop_index(op.f('ix_event_consumers_status'), table_name='event_consumers')
    op.drop_index('ix_event_consumers_event_id', table_name='event_consumers')
    op.drop_index('ix_event_consumers_consumer_name', table_name='event_consumers')
    op.drop_table('event_consumers')
    op.drop_table('audit_logs')
    op.drop_index(op.f('ix_api_tokens_user_id'), table_name='api_tokens')
    op.drop_index(op.f('ix_api_tokens_is_revoked'), table_name='api_tokens')
    op.drop_table('api_tokens')
    op.drop_index(op.f('ix_webhook_events_event_type'), table_name='webhook_events')
    op.drop_table('webhook_events')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_is_deleted'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_table('roles')
    op.drop_index(op.f('ix_permissions_code'), table_name='permissions')
    op.drop_table('permissions')
    op.drop_table('notification_templates')
    op.drop_index('ix_domain_events_is_published', table_name='domain_events')
    op.drop_index('ix_domain_events_event_type', table_name='domain_events')
    op.drop_index('ix_domain_events_aggregate_id', table_name='domain_events')
    op.drop_table('domain_events')
    op.drop_table('auth_providers')
    op.drop_index(op.f('ix_api_scopes_scope'), table_name='api_scopes')
    op.drop_table('api_scopes')
    # ### end Alembic commands ###
