"""add_module5_temporal_planning_scheduling

Revision ID: 53b8339a4b35
Revises: b65d6dfc8da8
Create Date: 2026-02-02 20:07:31.942205

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '53b8339a4b35'
down_revision = 'b65d6dfc8da8'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('holiday_calendars',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('holiday_date', sa.DateTime(timezone=True), nullable=False, comment='Date of holiday'),
    sa.Column('name', sa.String(length=255), nullable=False, comment="Holiday name (e.g., 'Christmas', 'Tet')"),
    sa.Column('is_recurring', sa.Boolean(), nullable=False, comment='Does it recur every year?'),
    sa.Column('created_by', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Timestamp when the record was created'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Timestamp when the record was last updated'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_holiday_calendars_created_by_users')),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], name=op.f('fk_holiday_calendars_workspace_id_workspaces')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_holiday_calendars')),
    sa.UniqueConstraint('workspace_id', 'holiday_date', name='uq_holiday_calendars_workspace_date')
    )
    op.create_index('ix_holiday_calendars_holiday_date', 'holiday_calendars', ['holiday_date'], unique=False)
    op.create_index('ix_holiday_calendars_workspace_id', 'holiday_calendars', ['workspace_id'], unique=False)
    op.create_table('working_hours_policies',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('working_days_mask', sa.Integer(), nullable=False, comment='Bitmask: 0=Mon...6=Sun. Default: Mon-Fri'),
    sa.Column('work_start_time', sa.String(length=8), nullable=False, comment='HH:MM format'),
    sa.Column('work_end_time', sa.String(length=8), nullable=False, comment='HH:MM format'),
    sa.Column('lunch_start_time', sa.String(length=8), nullable=True, comment='Optional lunch break start'),
    sa.Column('lunch_end_time', sa.String(length=8), nullable=True, comment='Optional lunch break end'),
    sa.Column('timezone', sa.String(length=50), nullable=False, comment='Timezone for schedule calculations'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Timestamp when the record was created'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Timestamp when the record was last updated'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], name=op.f('fk_working_hours_policies_workspace_id_workspaces')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_working_hours_policies'))
    )
    op.create_index('ix_working_hours_policies_workspace_id', 'working_hours_policies', ['workspace_id'], unique=False)
    op.create_table('personal_exceptions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('exception_date', sa.DateTime(timezone=True), nullable=False, comment='Date of exception'),
    sa.Column('exception_type', sa.String(length=50), nullable=False, comment='VACATION, SICK_LEAVE, HALF_DAY'),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Timestamp when the record was created'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Timestamp when the record was last updated'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('fk_personal_exceptions_project_id_projects')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_personal_exceptions_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_personal_exceptions'))
    )
    op.create_index('ix_personal_exceptions_exception_date', 'personal_exceptions', ['exception_date'], unique=False)
    op.create_index('ix_personal_exceptions_project_id', 'personal_exceptions', ['project_id'], unique=False)
    op.create_index('ix_personal_exceptions_user_id', 'personal_exceptions', ['user_id'], unique=False)
    op.create_table('plan_states',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('state', sa.String(length=50), nullable=False),
    sa.Column('submitted_by', sa.UUID(), nullable=True),
    sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('approved_by', sa.UUID(), nullable=True),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('locked_by', sa.UUID(), nullable=True),
    sa.Column('locked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True, comment='Approval notes or rejection reason'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Timestamp when the record was created'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Timestamp when the record was last updated'),
    sa.ForeignKeyConstraint(['approved_by'], ['users.id'], name=op.f('fk_plan_states_approved_by_users')),
    sa.ForeignKeyConstraint(['locked_by'], ['users.id'], name=op.f('fk_plan_states_locked_by_users')),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('fk_plan_states_project_id_projects')),
    sa.ForeignKeyConstraint(['submitted_by'], ['users.id'], name=op.f('fk_plan_states_submitted_by_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_plan_states'))
    )
    op.create_index('ix_plan_states_project_id', 'plan_states', ['project_id'], unique=False)
    op.create_table('resource_histograms',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('histogram_date', sa.DateTime(timezone=True), nullable=False, comment='Date of histogram calculation'),
    sa.Column('planned_hours', sa.Float(), nullable=False, comment='Planned working hours for this date'),
    sa.Column('is_overloaded', sa.Boolean(), nullable=False, comment='Is > 8 hours planned?'),
    sa.Column('overload_hours', sa.Float(), nullable=False, comment='Excess hours over 8'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Timestamp when the record was created'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Timestamp when the record was last updated'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('fk_resource_histograms_project_id_projects')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_resource_histograms_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_resource_histograms'))
    )
    op.create_index('ix_resource_histograms_histogram_date', 'resource_histograms', ['histogram_date'], unique=False)
    op.create_index('ix_resource_histograms_project_id', 'resource_histograms', ['project_id'], unique=False)
    op.create_index('ix_resource_histograms_user_id', 'resource_histograms', ['user_id'], unique=False)
    op.create_table('simulation_sessions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False, comment='Is simulation still running?'),
    sa.Column('delta_project_end_days', sa.Integer(), nullable=True, comment='Project end date shift (days)'),
    sa.Column('new_critical_path_count', sa.Integer(), nullable=True, comment='Number of tasks newly on critical path'),
    sa.Column('sla_at_risk_count', sa.Integer(), nullable=True, comment='Tasks at risk of SLA breach'),
    sa.Column('resource_overload_increase', sa.Integer(), nullable=True, comment='Additional overload instances'),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Timestamp when the record was created'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Timestamp when the record was last updated'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_simulation_sessions_created_by_users')),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('fk_simulation_sessions_project_id_projects')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_simulation_sessions'))
    )
    op.create_index('ix_simulation_sessions_is_active', 'simulation_sessions', ['is_active'], unique=False)
    op.create_index('ix_simulation_sessions_project_id', 'simulation_sessions', ['project_id'], unique=False)
    op.create_table('sla_policies',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('priority', sa.String(length=50), nullable=False, comment='CRITICAL, HIGH, MEDIUM, LOW'),
    sa.Column('sla_hours', sa.Integer(), nullable=False, comment='SLA target in working hours'),
    sa.Column('warning_threshold_percent', sa.Integer(), nullable=False, comment='Warn at X% of SLA time consumed'),
    sa.Column('enable_escalation', sa.Boolean(), nullable=False),
    sa.Column('escalation_level_1_hours', sa.Integer(), nullable=True, comment='Hours after breached for Level 1 escalation'),
    sa.Column('escalation_level_2_hours', sa.Integer(), nullable=True, comment='Hours after breached for Level 2 escalation'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Timestamp when the record was created'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Timestamp when the record was last updated'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('fk_sla_policies_project_id_projects')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_sla_policies')),
    sa.UniqueConstraint('project_id', 'priority', name='uq_sla_policies_project_priority')
    )
    op.create_index('ix_sla_policies_project_id', 'sla_policies', ['project_id'], unique=False)
    op.create_table('cross_project_dependencies',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('source_task_id', sa.UUID(), nullable=False, comment='Task in source project'),
    sa.Column('source_project_id', sa.UUID(), nullable=False),
    sa.Column('target_task_id', sa.UUID(), nullable=False, comment='Task in target project'),
    sa.Column('target_project_id', sa.UUID(), nullable=False),
    sa.Column('dependency_type', sa.String(length=10), nullable=False, comment='FS, SS, FF, SF'),
    sa.Column('is_broken', sa.Boolean(), nullable=False, comment='Broken link? (e.g., source task deleted)'),
    sa.Column('created_by', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Timestamp when the record was created'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Timestamp when the record was last updated'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_cross_project_dependencies_created_by_users')),
    sa.ForeignKeyConstraint(['source_project_id'], ['projects.id'], name=op.f('fk_cross_project_dependencies_source_project_id_projects')),
    sa.ForeignKeyConstraint(['source_task_id'], ['tasks.id'], name=op.f('fk_cross_project_dependencies_source_task_id_tasks')),
    sa.ForeignKeyConstraint(['target_project_id'], ['projects.id'], name=op.f('fk_cross_project_dependencies_target_project_id_projects')),
    sa.ForeignKeyConstraint(['target_task_id'], ['tasks.id'], name=op.f('fk_cross_project_dependencies_target_task_id_tasks')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_cross_project_dependencies')),
    sa.UniqueConstraint('source_task_id', 'target_task_id', name='uq_cross_project_dep_tasks')
    )
    op.create_index('ix_cross_project_dependencies_source', 'cross_project_dependencies', ['source_project_id', 'source_task_id'], unique=False)
    op.create_index('ix_cross_project_dependencies_target', 'cross_project_dependencies', ['target_project_id', 'target_task_id'], unique=False)
    op.create_table('planning_audit_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('task_id', sa.UUID(), nullable=False),
    sa.Column('change_type', sa.String(length=50), nullable=False, comment='START_DATE, END_DATE, DURATION, DEPENDENCY'),
    sa.Column('old_value', sa.Text(), nullable=True, comment='Previous value'),
    sa.Column('new_value', sa.Text(), nullable=False, comment='New value'),
    sa.Column('reason', sa.Text(), nullable=True, comment='Why was it changed?'),
    sa.Column('changed_by', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Timestamp when the record was created'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Timestamp when the record was last updated'),
    sa.ForeignKeyConstraint(['changed_by'], ['users.id'], name=op.f('fk_planning_audit_logs_changed_by_users')),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], name=op.f('fk_planning_audit_logs_task_id_tasks')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_planning_audit_logs'))
    )
    op.create_index('ix_planning_audit_logs_change_type', 'planning_audit_logs', ['change_type'], unique=False)
    op.create_index('ix_planning_audit_logs_changed_by', 'planning_audit_logs', ['changed_by'], unique=False)
    op.create_index('ix_planning_audit_logs_task_id', 'planning_audit_logs', ['task_id'], unique=False)
    op.create_table('planning_scopes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('task_id', sa.UUID(), nullable=False),
    sa.Column('include_in_planning', sa.Boolean(), nullable=False, comment='Include in Gantt, CPM, auto-scheduling'),
    sa.Column('override_parent', sa.Boolean(), nullable=False, comment="Override parent's scope setting?"),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Timestamp when the record was created'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Timestamp when the record was last updated'),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], name=op.f('fk_planning_scopes_task_id_tasks')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_planning_scopes')),
    sa.UniqueConstraint('task_id', name=op.f('uq_planning_scopes_task_id'))
    )
    op.create_index('ix_planning_scopes_task_id', 'planning_scopes', ['task_id'], unique=False)
    op.create_table('scheduling_modes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('task_id', sa.UUID(), nullable=False),
    sa.Column('mode', sa.String(length=50), nullable=False, comment='AUTO or MANUAL'),
    sa.Column('is_pinned', sa.Boolean(), nullable=False, comment='Pinned to specific dates'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Timestamp when the record was created'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Timestamp when the record was last updated'),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], name=op.f('fk_scheduling_modes_task_id_tasks')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_scheduling_modes')),
    sa.UniqueConstraint('task_id', name=op.f('uq_scheduling_modes_task_id'))
    )
    op.create_index('ix_scheduling_modes_task_id', 'scheduling_modes', ['task_id'], unique=False)
    op.create_table('sla_trackers',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('task_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False, comment='ON_TRACK, AT_RISK, BREACHED'),
    sa.Column('sla_start_time', sa.DateTime(timezone=True), nullable=False, comment='When SLA timer started (task -> IN_PROGRESS)'),
    sa.Column('sla_breach_time', sa.DateTime(timezone=True), nullable=True, comment='When SLA was breached (if any)'),
    sa.Column('sla_deadline', sa.DateTime(timezone=True), nullable=False, comment='Calculated SLA deadline in business time'),
    sa.Column('elapsed_business_seconds', sa.Integer(), nullable=False),
    sa.Column('paused_business_seconds', sa.Integer(), nullable=False, comment='Total paused time (e.g., waiting for customer)'),
    sa.Column('is_paused', sa.Boolean(), nullable=False, comment='Is timer currently paused?'),
    sa.Column('pause_reason', sa.String(length=255), nullable=True, comment='Why is timer paused? (e.g., Blocked, Waiting)'),
    sa.Column('paused_at', sa.DateTime(timezone=True), nullable=True, comment='When was timer paused?'),
    sa.Column('escalation_level_1_triggered', sa.Boolean(), nullable=False),
    sa.Column('escalation_level_1_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('escalation_level_2_triggered', sa.Boolean(), nullable=False),
    sa.Column('escalation_level_2_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Timestamp when the record was created'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Timestamp when the record was last updated'),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], name=op.f('fk_sla_trackers_task_id_tasks')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_sla_trackers')),
    sa.UniqueConstraint('task_id', name=op.f('uq_sla_trackers_task_id'))
    )
    op.create_index('ix_sla_trackers_status', 'sla_trackers', ['status'], unique=False)
    op.create_index('ix_sla_trackers_task_id', 'sla_trackers', ['task_id'], unique=False)
    op.create_table('task_baselines',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('task_id', sa.UUID(), nullable=False),
    sa.Column('baseline_version', sa.Integer(), nullable=False, comment='Baseline version number (1, 2, ...)'),
    sa.Column('baseline_start', sa.DateTime(timezone=True), nullable=False, comment='Planned start date at baseline creation'),
    sa.Column('baseline_end', sa.DateTime(timezone=True), nullable=False, comment='Planned end date at baseline creation'),
    sa.Column('baseline_duration_hours', sa.Float(), nullable=False, comment='Estimated hours at baseline creation'),
    sa.Column('actual_start', sa.DateTime(timezone=True), nullable=True, comment='Actual start date (when status -> IN_PROGRESS)'),
    sa.Column('actual_end', sa.DateTime(timezone=True), nullable=True, comment='Actual end date (when status -> DONE)'),
    sa.Column('actual_duration_hours', sa.Float(), nullable=True, comment='Actual hours spent'),
    sa.Column('schedule_variance_days', sa.Float(), nullable=True, comment='Difference between planned and actual start (days)'),
    sa.Column('created_by', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Timestamp when the record was created'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Timestamp when the record was last updated'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_task_baselines_created_by_users')),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], name=op.f('fk_task_baselines_task_id_tasks')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_task_baselines')),
    sa.UniqueConstraint('task_id', 'baseline_version', name='uq_task_baselines_task_version')
    )
    op.create_index('ix_task_baselines_baseline_version', 'task_baselines', ['baseline_version'], unique=False)
    op.create_index('ix_task_baselines_task_id', 'task_baselines', ['task_id'], unique=False)
    op.create_table('task_dependency_schedules',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('dependency_id', sa.UUID(), nullable=False),
    sa.Column('lag_days', sa.Integer(), nullable=False, comment='Positive: lag time (wait), negative: lead time (early start)'),
    sa.Column('is_auto_scheduled', sa.Boolean(), nullable=False, comment='Auto-schedule this dependency (Ref: Feature 2.2 AC 3)'),
    sa.Column('is_pinned', sa.Boolean(), nullable=False, comment='Pinned (manually scheduled) - cannot be auto-adjusted'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Timestamp when the record was created'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Timestamp when the record was last updated'),
    sa.ForeignKeyConstraint(['dependency_id'], ['task_dependencies.id'], name=op.f('fk_task_dependency_schedules_dependency_id_task_dependencies')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_task_dependency_schedules')),
    sa.UniqueConstraint('dependency_id', name='uq_task_dependency_schedules_dependency')
    )
    op.create_index('ix_task_dependency_schedules_dependency_id', 'task_dependency_schedules', ['dependency_id'], unique=False)
    op.drop_index('ix_workspace_invitations_token_hash', table_name='workspace_invitations')
    op.create_index('ix_workspace_invitations_token_hash', 'workspace_invitations', ['token_hash'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_workspace_invitations_token_hash', table_name='workspace_invitations')
    op.create_index('ix_workspace_invitations_token_hash', 'workspace_invitations', ['token_hash'], unique=True)
    op.drop_index('ix_task_dependency_schedules_dependency_id', table_name='task_dependency_schedules')
    op.drop_table('task_dependency_schedules')
    op.drop_index('ix_task_baselines_task_id', table_name='task_baselines')
    op.drop_index('ix_task_baselines_baseline_version', table_name='task_baselines')
    op.drop_table('task_baselines')
    op.drop_index('ix_sla_trackers_task_id', table_name='sla_trackers')
    op.drop_index('ix_sla_trackers_status', table_name='sla_trackers')
    op.drop_table('sla_trackers')
    op.drop_index('ix_scheduling_modes_task_id', table_name='scheduling_modes')
    op.drop_table('scheduling_modes')
    op.drop_index('ix_planning_scopes_task_id', table_name='planning_scopes')
    op.drop_table('planning_scopes')
    op.drop_index('ix_planning_audit_logs_task_id', table_name='planning_audit_logs')
    op.drop_index('ix_planning_audit_logs_changed_by', table_name='planning_audit_logs')
    op.drop_index('ix_planning_audit_logs_change_type', table_name='planning_audit_logs')
    op.drop_table('planning_audit_logs')
    op.drop_index('ix_cross_project_dependencies_target', table_name='cross_project_dependencies')
    op.drop_index('ix_cross_project_dependencies_source', table_name='cross_project_dependencies')
    op.drop_table('cross_project_dependencies')
    op.drop_index('ix_sla_policies_project_id', table_name='sla_policies')
    op.drop_table('sla_policies')
    op.drop_index('ix_simulation_sessions_project_id', table_name='simulation_sessions')
    op.drop_index('ix_simulation_sessions_is_active', table_name='simulation_sessions')
    op.drop_table('simulation_sessions')
    op.drop_index('ix_resource_histograms_user_id', table_name='resource_histograms')
    op.drop_index('ix_resource_histograms_project_id', table_name='resource_histograms')
    op.drop_index('ix_resource_histograms_histogram_date', table_name='resource_histograms')
    op.drop_table('resource_histograms')
    op.drop_index('ix_plan_states_project_id', table_name='plan_states')
    op.drop_table('plan_states')
    op.drop_index('ix_personal_exceptions_user_id', table_name='personal_exceptions')
    op.drop_index('ix_personal_exceptions_project_id', table_name='personal_exceptions')
    op.drop_index('ix_personal_exceptions_exception_date', table_name='personal_exceptions')
    op.drop_table('personal_exceptions')
    op.drop_index('ix_working_hours_policies_workspace_id', table_name='working_hours_policies')
    op.drop_table('working_hours_policies')
    op.drop_index('ix_holiday_calendars_workspace_id', table_name='holiday_calendars')
    op.drop_index('ix_holiday_calendars_holiday_date', table_name='holiday_calendars')
    op.drop_table('holiday_calendars')
    # ### end Alembic commands ###
