"""add_module4_task_execution

Revision ID: b65d6dfc8da8
Revises: module3_enhancements
Create Date: 2026-02-02 19:56:36.582969

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'b65d6dfc8da8'
down_revision = 'module3_enhancements'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('login_attempts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False, comment='Email attempted to login'),
    sa.Column('ip_address', sa.String(length=45), nullable=True, comment='IP address of login attempt'),
    sa.Column('user_agent', sa.Text(), nullable=True, comment='User agent of login attempt'),
    sa.Column('success', sa.Boolean(), nullable=False, comment='Whether login attempt was successful'),
    sa.Column('reason', sa.String(length=255), nullable=True, comment="Reason for failed attempt (e.g., 'Invalid password', 'Account locked')"),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Timestamp when the record was created'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Timestamp when the record was last updated'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_login_attempts'))
    )
    op.create_index(op.f('ix_login_attempts_email'), 'login_attempts', ['email'], unique=False)
    op.create_table('email_verification_tokens',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False, comment='Email to be verified'),
    sa.Column('token', sa.String(length=500), nullable=False, comment='One-time verification token (hashed)'),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False, comment='Token expiration time (default: 24 hours)'),
    sa.Column('verified_at', sa.DateTime(timezone=True), nullable=True, comment='When email was verified'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Timestamp when the record was created'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Timestamp when the record was last updated'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_email_verification_tokens_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_email_verification_tokens')),
    sa.UniqueConstraint('token', name=op.f('uq_email_verification_tokens_token'))
    )
    op.create_index(op.f('ix_email_verification_tokens_user_id'), 'email_verification_tokens', ['user_id'], unique=False)
    op.create_table('oauth_providers',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('provider', sa.String(length=50), nullable=False, comment='OAuth provider name (google, github, etc.)'),
    sa.Column('provider_user_id', sa.String(length=255), nullable=False, comment='User ID from OAuth provider'),
    sa.Column('provider_email', sa.String(length=255), nullable=False, comment='Email from OAuth provider'),
    sa.Column('access_token', sa.Text(), nullable=True, comment='OAuth access token (encrypted)'),
    sa.Column('refresh_token', sa.Text(), nullable=True, comment='OAuth refresh token (encrypted)'),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True, comment='Token expiration time'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Timestamp when the record was created'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Timestamp when the record was last updated'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_oauth_providers_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_oauth_providers'))
    )
    op.create_index('idx_oauth_provider_user', 'oauth_providers', ['provider', 'provider_user_id'], unique=True)
    op.create_index(op.f('ix_oauth_providers_user_id'), 'oauth_providers', ['user_id'], unique=False)
    op.create_table('password_reset_tokens',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('token', sa.String(length=500), nullable=False, comment='One-time reset token (hashed)'),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False, comment='Token expiration time (default: 15 minutes)'),
    sa.Column('used_at', sa.DateTime(timezone=True), nullable=True, comment='When token was used'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Timestamp when the record was created'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Timestamp when the record was last updated'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_password_reset_tokens_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_password_reset_tokens')),
    sa.UniqueConstraint('token', name=op.f('uq_password_reset_tokens_token'))
    )
    op.create_index(op.f('ix_password_reset_tokens_user_id'), 'password_reset_tokens', ['user_id'], unique=False)
    op.drop_table('auth_providers')
    
    # Create new enum types before altering columns
    op.execute("CREATE TYPE changerequeststatus AS ENUM ('DRAFT', 'PENDING', 'APPROVED', 'REJECTED', 'IMPLEMENTED', 'CANCELLED')")
    
    op.alter_column('project_change_requests', 'type',
               existing_type=postgresql.ENUM('SCOPE', 'SCHEDULE', 'COST', 'RESOURCE', name='changerequesttype'),
               server_default=None,
               existing_comment='Type of change request',
               existing_nullable=False)
    
    # Alter column to use new enum type - drop default first, then alter type
    op.execute("ALTER TABLE project_change_requests ALTER COLUMN status DROP DEFAULT")
    op.execute("ALTER TABLE project_change_requests ALTER COLUMN status TYPE changerequeststatus USING status::text::changerequeststatus")
    
    op.alter_column('projects', 'priority',
               existing_type=postgresql.ENUM('CRITICAL', 'HIGH', 'MEDIUM', 'LOW', name='projectpriority'),
               server_default=None,
               existing_comment='Project priority (CRITICAL / HIGH / MEDIUM / LOW)',
               existing_nullable=False)
    op.add_column('sessions', sa.Column('token', sa.String(length=500), nullable=False, comment='JWT token for this session'))
    op.add_column('sessions', sa.Column('user_agent', sa.Text(), nullable=True, comment='Full user agent string for device identification'))
    op.alter_column('sessions', 'device_info',
               existing_type=sa.VARCHAR(length=255),
               comment='Browser/device info (e.g., Chrome on Windows 10)',
               existing_nullable=True)
    op.alter_column('sessions', 'ip_address',
               existing_type=sa.VARCHAR(length=45),
               comment='Client IP address',
               existing_nullable=True)
    op.alter_column('sessions', 'geo_location',
               existing_type=sa.VARCHAR(length=100),
               comment='Estimated geographic location (city, country)',
               existing_nullable=True)
    op.alter_column('sessions', 'last_active_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='Last time this session was active',
               existing_nullable=False)
    op.alter_column('sessions', 'revoked_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='Timestamp when session was revoked/logged out',
               existing_nullable=True)
    op.create_index(op.f('ix_sessions_user_id'), 'sessions', ['user_id'], unique=False)
    op.create_unique_constraint(op.f('uq_sessions_token'), 'sessions', ['token'])
    op.drop_column('sessions', 'is_current')
    op.add_column('users', sa.Column('full_name', sa.String(length=255), nullable=True, comment="User's full name."))
    op.drop_index('ix_workspace_invitations_token_hash', table_name='workspace_invitations')
    op.create_index(op.f('ix_workspace_invitations_token_hash'), 'workspace_invitations', ['token_hash'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_workspace_invitations_token_hash'), table_name='workspace_invitations')
    op.create_index('ix_workspace_invitations_token_hash', 'workspace_invitations', ['token_hash'], unique=False)
    op.drop_column('users', 'full_name')
    op.add_column('sessions', sa.Column('is_current', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.drop_constraint(op.f('uq_sessions_token'), 'sessions', type_='unique')
    op.drop_index(op.f('ix_sessions_user_id'), table_name='sessions')
    op.alter_column('sessions', 'revoked_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='Timestamp when session was revoked/logged out',
               existing_nullable=True)
    op.alter_column('sessions', 'last_active_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='Last time this session was active',
               existing_nullable=False)
    op.alter_column('sessions', 'geo_location',
               existing_type=sa.VARCHAR(length=100),
               comment=None,
               existing_comment='Estimated geographic location (city, country)',
               existing_nullable=True)
    op.alter_column('sessions', 'ip_address',
               existing_type=sa.VARCHAR(length=45),
               comment=None,
               existing_comment='Client IP address',
               existing_nullable=True)
    op.alter_column('sessions', 'device_info',
               existing_type=sa.VARCHAR(length=255),
               comment=None,
               existing_comment='Browser/device info (e.g., Chrome on Windows 10)',
               existing_nullable=True)
    op.drop_column('sessions', 'user_agent')
    op.drop_column('sessions', 'token')
    op.alter_column('projects', 'priority',
               existing_type=postgresql.ENUM('CRITICAL', 'HIGH', 'MEDIUM', 'LOW', name='projectpriority'),
               server_default=sa.text("'MEDIUM'::projectpriority"),
               existing_comment='Project priority (CRITICAL / HIGH / MEDIUM / LOW)',
               existing_nullable=False)
    
    # Revert enum type change
    op.execute("ALTER TABLE project_change_requests ALTER COLUMN status TYPE change_request_status USING status::text::change_request_status")
    op.execute("DROP TYPE IF EXISTS changerequeststatus")
    
    op.alter_column('project_change_requests', 'type',
               existing_type=postgresql.ENUM('SCOPE', 'SCHEDULE', 'COST', 'RESOURCE', name='changerequesttype'),
               server_default=sa.text("'SCOPE'::changerequesttype"),
               existing_comment='Type of change request',
               existing_nullable=False)
    op.create_table('auth_providers',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('description', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False, comment='Timestamp when the record was created'),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False, comment='Timestamp when the record was last updated'),
    sa.PrimaryKeyConstraint('id', name='pk_auth_providers'),
    sa.UniqueConstraint('name', name='uq_auth_providers_name', postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.drop_index(op.f('ix_password_reset_tokens_user_id'), table_name='password_reset_tokens')
    op.drop_table('password_reset_tokens')
    op.drop_index(op.f('ix_oauth_providers_user_id'), table_name='oauth_providers')
    op.drop_index('idx_oauth_provider_user', table_name='oauth_providers')
    op.drop_table('oauth_providers')
    op.drop_index(op.f('ix_email_verification_tokens_user_id'), table_name='email_verification_tokens')
    op.drop_table('email_verification_tokens')
    op.drop_index(op.f('ix_login_attempts_email'), table_name='login_attempts')
    op.drop_table('login_attempts')
    # ### end Alembic commands ###
