"""add_module6_unified_collaboration

Revision ID: cd6041d7e8ce
Revises: 53b8339a4b35
Create Date: 2026-02-02 20:45:01.650794

"""
from alembic import op
import sqlalchemy as sa


attachment_status_enum = sa.Enum(
    'PENDING_SCAN', 'CLEAN', 'QUARANTINED', 'PROCESSING', 'READY',
    name='attachmentstatusenum'
)

approval_status_enum = sa.Enum(
    'PENDING', 'APPROVED', 'CHANGES_REQUESTED', 'REJECTED',
    name='approvalstatusenum'
)


# revision identifiers, used by Alembic.
revision = 'cd6041d7e8ce'
down_revision = '53b8339a4b35'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=True),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('parent_note_id', sa.UUID(), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('access_level', sa.Enum('PRIVATE', 'PROJECT', 'WORKSPACE', 'PUBLIC', name='noteaccessenum'), nullable=False),
    sa.Column('is_template', sa.Boolean(), nullable=False),
    sa.Column('template_name', sa.String(length=255), nullable=True),
    sa.Column('template_description', sa.Text(), nullable=True),
    sa.Column('template_category', sa.String(length=100), nullable=True),
    sa.Column('is_pinned', sa.Boolean(), nullable=False),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.Column('view_count', sa.Integer(), nullable=False),
    sa.Column('comment_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Timestamp when the record was created'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Timestamp when the record was last updated'),
    sa.ForeignKeyConstraint(['parent_note_id'], ['notes.id'], name=op.f('fk_notes_parent_note_id_notes'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('fk_notes_project_id_projects'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_notes_user_id_users'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_notes'))
    )
    op.create_index('ix_notes_access_level', 'notes', ['access_level'], unique=False)
    op.create_index('ix_notes_is_template', 'notes', ['is_template'], unique=False)
    op.create_index(op.f('ix_notes_parent_note_id'), 'notes', ['parent_note_id'], unique=False)
    op.create_index('ix_notes_project_created', 'notes', ['project_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_notes_project_id'), 'notes', ['project_id'], unique=False)
    op.create_index('ix_notes_project_title', 'notes', ['project_id', 'title'], unique=False)
    op.create_index('ix_notes_user_created', 'notes', ['user_id', 'created_at'], unique=False)
    op.create_table('search_indexes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('entity_type', sa.String(length=50), nullable=False),
    sa.Column('entity_id', sa.String(length=36), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('snippet', sa.String(length=500), nullable=True),
    sa.Column('url_path', sa.String(length=500), nullable=True),
    sa.Column('created_by', sa.String(length=36), nullable=True),
    sa.Column('original_created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Timestamp when the record was created'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Timestamp when the record was last updated'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('fk_search_indexes_project_id_projects'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_search_indexes'))
    )
    op.create_index('ix_search_indexes_entity', 'search_indexes', ['entity_type', 'entity_id'], unique=False)
    op.create_index(op.f('ix_search_indexes_entity_id'), 'search_indexes', ['entity_id'], unique=False)
    op.create_index('ix_search_indexes_project', 'search_indexes', ['project_id'], unique=False)
    op.create_table('note_versions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('note_id', sa.UUID(), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=False),
    sa.Column('version_number', sa.Integer(), nullable=False),
    sa.Column('change_description', sa.String(length=255), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('added_content', sa.Text(), nullable=True),
    sa.Column('removed_content', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Timestamp when the record was created'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Timestamp when the record was last updated'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_note_versions_created_by_users'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['note_id'], ['notes.id'], name=op.f('fk_note_versions_note_id_notes'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_note_versions')),
    sa.UniqueConstraint('note_id', 'version_number', name='uq_note_version_number')
    )
    op.create_index('ix_note_versions_created', 'note_versions', ['created_at'], unique=False)
    op.create_index(op.f('ix_note_versions_note_id'), 'note_versions', ['note_id'], unique=False)
    op.create_table('public_links',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('note_id', sa.UUID(), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=False),
    sa.Column('slug', sa.String(length=100), nullable=False),
    sa.Column('link_title', sa.String(length=255), nullable=True),
    sa.Column('password_hash', sa.String(length=255), nullable=True),
    sa.Column('is_password_protected', sa.Boolean(), nullable=False),
    sa.Column('expiration_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.Enum('ACTIVE', 'EXPIRED', 'DISABLED', 'PASSWORD_PROTECTED', name='publiclinkstatusenum'), nullable=False),
    sa.Column('view_count', sa.Integer(), nullable=False),
    sa.Column('last_accessed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('auto_update', sa.Boolean(), nullable=False),
    sa.Column('last_published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Timestamp when the record was created'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Timestamp when the record was last updated'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_public_links_created_by_users'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['note_id'], ['notes.id'], name=op.f('fk_public_links_note_id_notes'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_public_links'))
    )
    op.create_index('ix_public_links_expiration', 'public_links', ['expiration_date'], unique=False)
    op.create_index('ix_public_links_note', 'public_links', ['note_id'], unique=False)
    op.create_index(op.f('ix_public_links_note_id'), 'public_links', ['note_id'], unique=False)
    op.create_index(op.f('ix_public_links_slug'), 'public_links', ['slug'], unique=True)
    op.create_index('ix_public_links_status', 'public_links', ['status'], unique=False)
    op.create_table('smart_backlinks',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('note_id', sa.UUID(), nullable=False),
    sa.Column('source_note_id', sa.UUID(), nullable=True),
    sa.Column('source_task_id', sa.UUID(), nullable=True),
    sa.Column('mention_text', sa.String(length=255), nullable=False),
    sa.Column('is_linked', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Timestamp when the record was created'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Timestamp when the record was last updated'),
    sa.ForeignKeyConstraint(['note_id'], ['notes.id'], name=op.f('fk_smart_backlinks_note_id_notes'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_note_id'], ['notes.id'], name=op.f('fk_smart_backlinks_source_note_id_notes'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_task_id'], ['tasks.id'], name=op.f('fk_smart_backlinks_source_task_id_tasks'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_smart_backlinks'))
    )
    op.create_index('ix_smart_backlinks_note', 'smart_backlinks', ['note_id'], unique=False)
    op.create_index(op.f('ix_smart_backlinks_note_id'), 'smart_backlinks', ['note_id'], unique=False)
    op.create_index('ix_smart_backlinks_source_note', 'smart_backlinks', ['source_note_id'], unique=False)
    op.create_table('user_presence',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('task_id', sa.UUID(), nullable=True),
    sa.Column('note_id', sa.UUID(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('is_typing', sa.Boolean(), nullable=False),
    sa.Column('last_activity_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('session_id', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Timestamp when the record was created'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Timestamp when the record was last updated'),
    sa.ForeignKeyConstraint(['note_id'], ['notes.id'], name=op.f('fk_user_presence_note_id_notes'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], name=op.f('fk_user_presence_task_id_tasks'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_user_presence_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_user_presence'))
    )
    op.create_index('ix_user_presence_note', 'user_presence', ['note_id'], unique=False)
    op.create_index(op.f('ix_user_presence_note_id'), 'user_presence', ['note_id'], unique=False)
    op.create_index('ix_user_presence_task', 'user_presence', ['task_id'], unique=False)
    op.create_index(op.f('ix_user_presence_task_id'), 'user_presence', ['task_id'], unique=False)
    op.create_index('ix_user_presence_user', 'user_presence', ['user_id'], unique=False)
    op.create_index(op.f('ix_user_presence_user_id'), 'user_presence', ['user_id'], unique=False)
    op.create_table('approval_records',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('task_id', sa.UUID(), nullable=True),
    sa.Column('file_id', sa.UUID(), nullable=True),
    sa.Column('approver_id', sa.UUID(), nullable=False),
    sa.Column('requestor_id', sa.UUID(), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'APPROVED', 'CHANGES_REQUESTED', 'REJECTED', name='approvalstatusenum'), nullable=False),
    sa.Column('decision_notes', sa.Text(), nullable=True),
    sa.Column('decision_timestamp', sa.DateTime(timezone=True), nullable=True),
    sa.Column('checksum', sa.String(length=64), nullable=False),
    sa.Column('signature', sa.String(length=500), nullable=True),
    sa.Column('invalidation_reason', sa.String(length=255), nullable=True),
    sa.Column('invalidated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('invalidation_checksum', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Timestamp when the record was created'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Timestamp when the record was last updated'),
    sa.ForeignKeyConstraint(['approver_id'], ['users.id'], name=op.f('fk_approval_records_approver_id_users'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['file_id'], ['files.id'], name=op.f('fk_approval_records_file_id_files'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['requestor_id'], ['users.id'], name=op.f('fk_approval_records_requestor_id_users'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], name=op.f('fk_approval_records_task_id_tasks'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_approval_records'))
    )
    op.create_index('ix_approval_records_approver', 'approval_records', ['approver_id'], unique=False)
    op.create_index('ix_approval_records_file', 'approval_records', ['file_id'], unique=False)
    op.create_index(op.f('ix_approval_records_file_id'), 'approval_records', ['file_id'], unique=False)
    op.create_index('ix_approval_records_status', 'approval_records', ['status'], unique=False)
    op.create_index('ix_approval_records_task', 'approval_records', ['task_id'], unique=False)
    op.create_index(op.f('ix_approval_records_task_id'), 'approval_records', ['task_id'], unique=False)
    op.create_table('collaboration_notifications',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('recipient_user_id', sa.UUID(), nullable=False),
    sa.Column('trigger_type', sa.String(length=50), nullable=False),
    sa.Column('task_id', sa.UUID(), nullable=True),
    sa.Column('note_id', sa.UUID(), nullable=True),
    sa.Column('comment_id', sa.UUID(), nullable=True),
    sa.Column('triggered_by_user_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('read_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Timestamp when the record was created'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Timestamp when the record was last updated'),
    sa.ForeignKeyConstraint(['comment_id'], ['comments.id'], name=op.f('fk_collaboration_notifications_comment_id_comments'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['note_id'], ['notes.id'], name=op.f('fk_collaboration_notifications_note_id_notes'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['recipient_user_id'], ['users.id'], name=op.f('fk_collaboration_notifications_recipient_user_id_users'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], name=op.f('fk_collaboration_notifications_task_id_tasks'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['triggered_by_user_id'], ['users.id'], name=op.f('fk_collaboration_notifications_triggered_by_user_id_users'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_collaboration_notifications'))
    )
    op.create_index('ix_collaboration_notifications_created', 'collaboration_notifications', ['created_at'], unique=False)
    op.create_index('ix_collaboration_notifications_is_read', 'collaboration_notifications', ['is_read'], unique=False)
    op.create_index('ix_collaboration_notifications_recipient', 'collaboration_notifications', ['recipient_user_id'], unique=False)
    op.create_index(op.f('ix_collaboration_notifications_recipient_user_id'), 'collaboration_notifications', ['recipient_user_id'], unique=False)
    op.create_table('mentions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('mentioned_user_id', sa.UUID(), nullable=False),
    sa.Column('mentioned_by_user_id', sa.UUID(), nullable=False),
    sa.Column('comment_id', sa.UUID(), nullable=True),
    sa.Column('note_id', sa.UUID(), nullable=True),
    sa.Column('mention_priority', sa.Integer(), nullable=False),
    sa.Column('context', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Timestamp when the record was created'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Timestamp when the record was last updated'),
    sa.ForeignKeyConstraint(['comment_id'], ['comments.id'], name=op.f('fk_mentions_comment_id_comments'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['mentioned_by_user_id'], ['users.id'], name=op.f('fk_mentions_mentioned_by_user_id_users'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['mentioned_user_id'], ['users.id'], name=op.f('fk_mentions_mentioned_user_id_users'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['note_id'], ['notes.id'], name=op.f('fk_mentions_note_id_notes'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_mentions'))
    )
    op.create_index('ix_mentions_comment', 'mentions', ['comment_id'], unique=False)
    op.create_index('ix_mentions_mentioned_by_user', 'mentions', ['mentioned_by_user_id'], unique=False)
    op.create_index('ix_mentions_mentioned_user', 'mentions', ['mentioned_user_id'], unique=False)
    op.create_index(op.f('ix_mentions_mentioned_user_id'), 'mentions', ['mentioned_user_id'], unique=False)

    attachment_status_enum.create(op.get_bind(), checkfirst=True)
    approval_status_enum.create(op.get_bind(), checkfirst=True)

    op.add_column('comments', sa.Column('mentioned_user_ids', sa.JSON(), nullable=True, comment='List of mentioned user IDs'))
    op.add_column('comments', sa.Column('original_content', sa.Text(), nullable=True, comment='Original content before edits'))
    op.add_column('comments', sa.Column('edit_count', sa.Integer(), nullable=False, comment='Number of edits'))
    op.add_column('comments', sa.Column('reply_count', sa.Integer(), nullable=False, comment='Number of replies'))
    op.add_column('comments', sa.Column('is_pinned', sa.Boolean(), nullable=False, comment='Whether comment is pinned'))
    op.add_column('comments', sa.Column('reactions', sa.JSON(), nullable=True, comment='Emoji reactions with user IDs'))
    op.add_column('file_versions', sa.Column('checksum', sa.String(length=64), nullable=True, comment='SHA256 checksum for this version'))
    op.add_column('files', sa.Column('storage_provider', sa.String(length=50), nullable=False, comment='Storage provider (local, s3, azure)'))
    op.add_column('files', sa.Column('status', sa.Enum('PENDING_SCAN', 'CLEAN', 'QUARANTINED', 'PROCESSING', 'READY', name='attachmentstatusenum'), nullable=False, comment='Virus scan and preview status'))
    op.add_column('files', sa.Column('scan_result', sa.String(length=50), nullable=True, comment='Scan result (clean, quarantined, malicious)'))
    op.add_column('files', sa.Column('preview_url', sa.String(length=500), nullable=True, comment='Preview URL if generated'))
    op.add_column('files', sa.Column('preview_generated', sa.Boolean(), nullable=False, comment='Whether preview was generated'))
    op.add_column('files', sa.Column('approval_status', sa.Enum('PENDING', 'APPROVED', 'CHANGES_REQUESTED', 'REJECTED', name='approvalstatusenum'), nullable=False, comment='Approval status for this file'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('files', 'approval_status')
    op.drop_column('files', 'preview_generated')
    op.drop_column('files', 'preview_url')
    op.drop_column('files', 'scan_result')
    op.drop_column('files', 'status')
    op.drop_column('files', 'storage_provider')
    op.drop_column('file_versions', 'checksum')
    op.drop_column('comments', 'reactions')
    op.drop_column('comments', 'is_pinned')
    op.drop_column('comments', 'reply_count')
    op.drop_column('comments', 'edit_count')
    op.drop_column('comments', 'original_content')
    op.drop_column('comments', 'mentioned_user_ids')
    op.drop_index(op.f('ix_mentions_mentioned_user_id'), table_name='mentions')
    op.drop_index('ix_mentions_mentioned_user', table_name='mentions')
    op.drop_index('ix_mentions_mentioned_by_user', table_name='mentions')
    op.drop_index('ix_mentions_comment', table_name='mentions')
    op.drop_table('mentions')
    op.drop_index(op.f('ix_collaboration_notifications_recipient_user_id'), table_name='collaboration_notifications')
    op.drop_index('ix_collaboration_notifications_recipient', table_name='collaboration_notifications')
    op.drop_index('ix_collaboration_notifications_is_read', table_name='collaboration_notifications')
    op.drop_index('ix_collaboration_notifications_created', table_name='collaboration_notifications')
    op.drop_table('collaboration_notifications')
    op.drop_index(op.f('ix_approval_records_task_id'), table_name='approval_records')
    op.drop_index('ix_approval_records_task', table_name='approval_records')
    op.drop_index('ix_approval_records_status', table_name='approval_records')
    op.drop_index(op.f('ix_approval_records_file_id'), table_name='approval_records')
    op.drop_index('ix_approval_records_file', table_name='approval_records')
    op.drop_index('ix_approval_records_approver', table_name='approval_records')
    op.drop_table('approval_records')
    op.drop_index(op.f('ix_user_presence_user_id'), table_name='user_presence')
    op.drop_index('ix_user_presence_user', table_name='user_presence')
    op.drop_index(op.f('ix_user_presence_task_id'), table_name='user_presence')
    op.drop_index('ix_user_presence_task', table_name='user_presence')
    op.drop_index(op.f('ix_user_presence_note_id'), table_name='user_presence')
    op.drop_index('ix_user_presence_note', table_name='user_presence')
    op.drop_table('user_presence')
    op.drop_index('ix_smart_backlinks_source_note', table_name='smart_backlinks')
    op.drop_index(op.f('ix_smart_backlinks_note_id'), table_name='smart_backlinks')
    op.drop_index('ix_smart_backlinks_note', table_name='smart_backlinks')
    op.drop_table('smart_backlinks')
    op.drop_index('ix_public_links_status', table_name='public_links')
    op.drop_index(op.f('ix_public_links_slug'), table_name='public_links')
    op.drop_index(op.f('ix_public_links_note_id'), table_name='public_links')
    op.drop_index('ix_public_links_note', table_name='public_links')
    op.drop_index('ix_public_links_expiration', table_name='public_links')
    op.drop_table('public_links')
    op.drop_index(op.f('ix_note_versions_note_id'), table_name='note_versions')
    op.drop_index('ix_note_versions_created', table_name='note_versions')
    op.drop_table('note_versions')
    op.drop_index('ix_search_indexes_project', table_name='search_indexes')
    op.drop_index(op.f('ix_search_indexes_entity_id'), table_name='search_indexes')
    op.drop_index('ix_search_indexes_entity', table_name='search_indexes')
    op.drop_table('search_indexes')
    op.drop_index('ix_notes_user_created', table_name='notes')
    op.drop_index('ix_notes_project_title', table_name='notes')
    op.drop_index(op.f('ix_notes_project_id'), table_name='notes')
    op.drop_index('ix_notes_project_created', table_name='notes')
    op.drop_index(op.f('ix_notes_parent_note_id'), table_name='notes')
    op.drop_index('ix_notes_is_template', table_name='notes')
    op.drop_index('ix_notes_access_level', table_name='notes')
    op.drop_table('notes')

    approval_status_enum.drop(op.get_bind(), checkfirst=True)
    attachment_status_enum.drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
